/* CONTRABAND — the catalog (single source of truth for the hub).

   Every entry is a book that is (a) widely taught in U.S. grades 6–12 and
   (b) challenged or removed in U.S. school districts. We index them here as a
   defense of the freedom to read, not as an endorsement of any one edition.

   status:
     "available" — a Contraband learning room exists → set href
     "building"  — room is planned; copyrighted works are built one at a time
                   with the teacher's own text (paraphrase-only, quotation-free)

   themes (stable keys, translated for display by the hub):
     justice  — Social justice, civil rights, equity
     history  — Actual history & collective memory (Holocaust, slavery, internment)
     identity — Identity, coming of age, DEI, belonging
     power    — Censorship, propaganda, and power itself

   summary — a short, spoiler-light "CliffsNotes-lite" plot line for cards + posters.
   rights  — "public-domain" | "copyrighted"  (copyrighted → companion-only room)
*/
window.CONTRABAND_TITLES = [

  /* ─────────────  GRADES 6–8  ───────────── */
  {
    id: "annefrank",
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    year: "1947",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["history", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "annefrank/",
    accent: "#8a6d3b",
    summary: "A Jewish teenager hiding from the Nazis in a secret annex records two years of fear, hope, and ordinary growing-up in her diary — until the hiding place is discovered.",
    why: "A girl in hiding from the Nazis — challenged for its frank passages on growing up and, absurdly, for being 'a real downer.' The record of the Holocaust told from inside it.",
  },
  {
    id: "rollofthunder",
    title: "Roll of Thunder, Hear My Cry",
    author: "Mildred D. Taylor",
    year: "1976",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "rollofthunder/",
    accent: "#b0472e",
    summary: "In Depression-era Mississippi, nine-year-old Cassie Logan and her family fight to keep their own land and their dignity against the daily cruelties of Jim Crow, as quiet endurance turns into open resistance.",
    why: "A Black family holds onto its land and its dignity in Depression-era Mississippi. Challenged for racial slurs the book depicts to indict them.",
  },
  {
    id: "watsons",
    title: "The Watsons Go to Birmingham — 1963",
    author: "Christopher Paul Curtis",
    year: "1995",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "watsons/",
    accent: "#c9822b",
    summary: "The loving, funny Watson family drives from Michigan to Birmingham, Alabama in 1963 — and arrives just as history turns violent at the 16th Street Baptist Church.",
    why: "A funny, tender family road trip that drives straight into the 16th Street Baptist Church bombing. Challenged over violence and its portrayal of racism.",
  },
  {
    id: "numberthestars",
    title: "Number the Stars",
    author: "Lois Lowry",
    year: "1989",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["history", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "numberthestars/",
    accent: "#3a5a8c",
    summary: "In Nazi-occupied Denmark, ten-year-old Annemarie helps her family smuggle her Jewish best friend to safety across the sea — an ordinary girl who finds extraordinary courage.",
    why: "Danish children help smuggle Jewish neighbors to safety. Challenged for Holocaust content deemed too intense — courage under occupation, at a child's eye level.",
  },
  {
    id: "browngirl",
    title: "Brown Girl Dreaming",
    author: "Jacqueline Woodson",
    year: "2014",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "browngirl/",
    accent: "#7a4fce",
    summary: "In lyrical verse, Jacqueline Woodson remembers growing up Black in the 1960s and '70s, between South Carolina and New York, discovering her own voice as a writer.",
    why: "A memoir in verse of growing up Black in the 1960s–70s, between South and North. Challenged for its honest civil-rights history and religion.",
  },
  {
    id: "newkid",
    title: "New Kid",
    author: "Jerry Craft",
    year: "2019",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "newkid/",
    accent: "#d98a2b",
    summary: "Jordan, a Black seventh-grader who loves to draw, is sent to a mostly-white private school far from home and learns to navigate two very different worlds. A funny, honest graphic novel about fitting in.",
    why: "A Newbery-winning graphic novel about a Black seventh-grader at a mostly-white prep school. Pulled from school events over false 'critical race theory' claims.",
  },
  {
    id: "esperanza",
    title: "Esperanza Rising",
    author: "Pam Muñoz Ryan",
    year: "2000",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "history", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "esperanza/",
    accent: "#bf5a3a",
    summary: "A wealthy Mexican girl loses everything and must start over as a farm laborer in Depression-era California, discovering resilience, dignity, and solidarity.",
    why: "A wealthy Mexican girl becomes a farmworker in Depression-era California. Challenged over labor organizing, deportation, and class.",
  },
  {
    id: "insideout",
    title: "Inside Out & Back Again",
    author: "Thanhhà Lại",
    year: "2011",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "insideout/",
    accent: "#2f8f8f",
    summary: "Told in verse, ten-year-old Hà flees the fall of Saigon with her family and struggles to rebuild her life — and her sense of self — in Alabama.",
    why: "A verse novel of a girl fleeing the fall of Saigon and remaking herself in Alabama. Challenged over the refugee and war content it exists to teach.",
  },
  {
    id: "ghostboys",
    title: "Ghost Boys",
    author: "Jewell Parker Rhodes",
    year: "2018",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice"],
    rights: "copyrighted",
    status: "available",
    href: "ghostboys/",
    accent: "#4a4f6b",
    summary: "After twelve-year-old Jerome is killed by a police officer who mistook his toy gun for a real one, his ghost witnesses the aftermath and meets the ghost of Emmett Till.",
    why: "A twelve-year-old is killed by police and, as a ghost, meets Emmett Till. Among the most-challenged books in the country over race and policing.",
  },

  /* ─────────────  GRADES 9–12  ───────────── */
  {
    id: "douglass",
    title: "Narrative of the Life of Frederick Douglass",
    author: "Frederick Douglass",
    year: "1845",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history", "power"],
    rights: "public-domain",
    status: "available",
    href: "douglass/",
    accent: "#6b4f2a",
    sample: true,
    summary: "The most famous of the slave narratives: Frederick Douglass's own account of his life in bondage, his secret path to literacy, and his escape to freedom.",
    why: "A formerly enslaved man's first-person testimony against slavery — long challenged, and exactly the kind of hard history being pulled from shelves. In the public domain and free to read.",
  },
  {
    id: "mockingbird",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    year: "1960",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "mockingbird/",
    accent: "#6a7a4a",
    summary: "In a small Alabama town during the Depression, young Scout Finch watches her father, lawyer Atticus Finch, defend a Black man falsely accused of rape. A coming-of-age story about conscience and injustice.",
    why: "The trial of a Black man falsely accused in the Jim Crow South. Perennially challenged for racial slurs — and for making readers sit with injustice.",
  },
  {
    id: "huckfinn",
    title: "The Adventures of Huckleberry Finn",
    author: "Mark Twain",
    year: "1884",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history", "power"],
    rights: "public-domain",
    status: "available",
    href: "huckfinn/",
    accent: "#7a6a35",
    summary: "Huck Finn and Jim, a man escaping slavery, raft down the Mississippi River, forging a friendship that defies everything their society taught them.",
    why: "A runaway boy and a man escaping slavery raft down the Mississippi. One of the most-banned books in America — for its language and its indictment of that language's world.",
  },
  {
    id: "night",
    title: "Night",
    author: "Elie Wiesel",
    year: "1960",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history"],
    rights: "copyrighted",
    status: "available",
    href: "night/",
    accent: "#6b6f76",
    summary: "Elie Wiesel's memoir of surviving the Nazi camps of Auschwitz and Buchenwald as a teenager — and of holding onto, and losing, his faith in the darkness.",
    why: "A survivor's memoir of Auschwitz and Buchenwald. Challenged as too dark or too religious — the testimony a Nobel laureate spent his life insisting we not forget.",
  },
  {
    id: "maus",
    title: "Maus: A Survivor's Tale",
    author: "Art Spiegelman",
    year: "1986",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history", "power"],
    rights: "copyrighted",
    status: "available",
    href: "maus/",
    accent: "#5f5f5f",
    summary: "Art Spiegelman retells his father's survival of the Holocaust as a graphic memoir — Jews drawn as mice, Nazis as cats — while wrestling with his father's memory in the present.",
    why: "A Pulitzer-winning graphic memoir of the Holocaust, mice and cats. Removed by a school board over a few words and a drawing.",
  },
  {
    id: "bluesteye",
    title: "The Bluest Eye",
    author: "Toni Morrison",
    year: "1970",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "bluesteye/",
    accent: "#4a6d8c",
    summary: "In 1940s Ohio, a young Black girl named Pecola, told she is ugly by everyone around her, prays for blue eyes. Toni Morrison's unflinching first novel about beauty, race, and self-worth.",
    why: "A Black girl in 1940s Ohio prays for blue eyes. A Nobel laureate's study of internalized racism — among the most-targeted books in the country.",
  },
  {
    id: "theireyes",
    title: "Their Eyes Were Watching God",
    author: "Zora Neale Hurston",
    year: "1937",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "theireyes/",
    accent: "#8a5a2b",
    summary: "Janie Crawford searches for love and her own voice across three marriages in the Black communities of early-1900s Florida. A landmark of American literature.",
    why: "A Black woman in early-20th-century Florida claims her own voice and desire. Challenged over language and sexuality; a cornerstone of the American canon.",
  },
  {
    id: "cagedbird",
    title: "I Know Why the Caged Bird Sings",
    author: "Maya Angelou",
    year: "1969",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "cagedbird/",
    accent: "#9a6b3a",
    summary: "Maya Angelou's memoir of growing up Black and female in the segregated South — surviving trauma and finding strength in words, family, and community.",
    why: "Angelou's memoir of a Black girlhood in the segregated South, including surviving assault. One of the most-banned books of the last 40 years.",
  },
  {
    id: "parttimeindian",
    title: "The Absolutely True Diary of a Part-Time Indian",
    author: "Sherman Alexie",
    year: "2007",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "parttimeindian/",
    accent: "#3a6a5a",
    summary: "Arnold 'Junior' Spirit, a budding cartoonist, leaves his troubled reservation school for an all-white town high school, straddling two worlds. Funny, heartbreaking, and honest.",
    why: "A budget-award memoir-novel of a Spokane teen who transfers to an all-white school. Challenged over language, poverty, and Native experience.",
  },
  {
    id: "hateugive",
    title: "The Hate U Give",
    author: "Angie Thomas",
    year: "2017",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "hateugive/",
    accent: "#b0341f",
    summary: "Sixteen-year-old Starr is the only witness when her unarmed friend is shot by a police officer. Torn between her poor neighborhood and her wealthy school, she has to decide whether to speak out.",
    why: "A teen witnesses a police shooting of her friend and finds her voice. One of the decade's most-challenged books over 'anti-police' and language claims.",
  },
  {
    id: "allamericanboys",
    title: "All American Boys",
    author: "Jason Reynolds & Brendan Kiely",
    year: "2015",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "allamericanboys/",
    accent: "#2f5f9e",
    summary: "After a Black teen is beaten by a white police officer, two boys — the victim and a white classmate who saw it — tell the story from both sides as their town takes sides.",
    why: "Two teens — one Black, one white — reckon with a police beating from both sides. Widely challenged and pulled over race and policing.",
  },
  {
    id: "stamped",
    title: "Stamped: Racism, Antiracism, and You",
    author: "Jason Reynolds & Ibram X. Kendi",
    year: "2020",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history", "justice", "power"],
    rights: "copyrighted",
    status: "available",
    href: "stamped/",
    accent: "#b8231f",
    summary: "A fast, teen-friendly history of racist ideas in America — where they came from, how they persist, and how to be antiracist. Nonfiction that reads like a conversation.",
    why: "A teen 'remix' of the history of racist ideas in America. A lightning rod in book-challenge fights and district removals.",
  },
  {
    id: "justmercy",
    title: "Just Mercy (Adapted for Young Adults)",
    author: "Bryan Stevenson",
    year: "2018",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "power"],
    rights: "copyrighted",
    status: "available",
    href: "justmercy/",
    accent: "#5f6b3a",
    summary: "Lawyer Bryan Stevenson's true account of defending the wrongly condemned — especially Walter McMillian, an innocent man on Alabama's death row — and of mercy in a broken justice system.",
    why: "A lawyer's true account of the wrongly condemned and a broken justice system. Challenged over its portrait of race and the death penalty.",
  },
  {
    id: "mangostreet",
    title: "The House on Mango Street",
    author: "Sandra Cisneros",
    year: "1984",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "mangostreet/",
    accent: "#c96b3a",
    summary: "In a series of short, poetic vignettes, a young Latina named Esperanza comes of age on a poor Chicago street and dreams of a house — and a life — of her own.",
    why: "A Latina girl in Chicago writes herself a way out. Challenged over mature vignettes; a staple of American and Mexican-American literature courses.",
  },
  {
    id: "persepolis",
    title: "Persepolis",
    author: "Marjane Satrapi",
    year: "2003",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history", "power", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "persepolis/",
    accent: "#7a1f2a",
    summary: "In a black-and-white graphic memoir, Marjane Satrapi recalls growing up as a rebellious girl during and after Iran's Islamic Revolution.",
    why: "A graphic memoir of growing up during Iran's revolution. Famously yanked from Chicago classrooms and challenged elsewhere over 'graphic' scenes of state violence.",
  },
  {
    id: "manzanar",
    title: "Farewell to Manzanar",
    author: "Jeanne Wakatsuki Houston & James D. Houston",
    year: "1973",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "manzanar/",
    accent: "#6a6a55",
    summary: "Jeanne Wakatsuki Houston's memoir of her family's imprisonment at the Manzanar internment camp during World War II, and its lasting effect on their lives.",
    why: "A firsthand account of a Japanese-American family imprisoned in a U.S. internment camp. Challenged for the very history it documents.",
  },
  {
    id: "butterflies",
    title: "In the Time of the Butterflies",
    author: "Julia Alvarez",
    year: "1994",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history", "power"],
    rights: "copyrighted",
    status: "available",
    href: "butterflies/",
    accent: "#b5462f",
    summary: "In the Dominican Republic under the Trujillo dictatorship, the four Mirabal sisters join the resistance — and three are murdered for it. Based on a true story.",
    why: "The Mirabal sisters resist a dictatorship in the Dominican Republic — and pay for it. Challenged over violence and politics; a lesson in courage and memory.",
  },
  {
    id: "kindred",
    title: "Kindred",
    author: "Octavia E. Butler",
    year: "1979",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "kindred/",
    accent: "#6a3d8a",
    summary: "A modern Black woman is repeatedly pulled back in time to an antebellum Maryland plantation, where she must survive slavery to ensure her own family's future.",
    why: "A modern Black woman is pulled back in time to an antebellum plantation. Challenged over its unflinching depiction of slavery's violence.",
  },
  {
    id: "separate",
    title: "Separate Is Never Equal",
    author: "Duncan Tonatiuh",
    year: "2014",
    gradeBand: "6-8",
    grades: "4–7",
    themes: ["justice", "history", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "separate/",
    accent: "#2f7d6b",
    summary: "The true story of Sylvia Mendez and her family's fight to end school segregation in 1940s California — the Mendez v. Westminster case that helped pave the way for Brown v. Board of Education.",
    why: "A picture-book history of Latino school desegregation. Challenged over how it teaches racism, segregation, and civil-rights history to younger readers.",
  },
  {
    id: "bnw",
    title: "Brave New World",
    author: "Aldous Huxley",
    year: "1932",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["power"],
    rights: "copyrighted",
    status: "available",
    href: "bnw/",
    accent: "#3f6d7a",
    summary: "In a future where people are engineered and drugged into contentment, a few misfits confront what freedom and humanity really cost. Huxley's classic dystopia.",
    why: "An engineered society trades freedom for comfort. Banned and challenged for decades — a book about control that keeps getting controlled.",
  },

  /* ─────────────  Dystopia & censorship  ───────────── */
  {
    id: "fahrenheit451",
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    year: "1953",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["power"],
    rights: "copyrighted",
    status: "available",
    href: "fahrenheit451/",
    accent: "#c1272d",
    summary: "In a future where firemen start fires to burn books, one fireman begins to wonder what the pages are worth.",
    why: "A novel about burning books that has itself been challenged and censored for decades — the patron saint of any banned-book collection.",
  },
  {
    id: "nineteeneightyfour",
    title: "1984",
    author: "George Orwell",
    year: "1949",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["power"],
    rights: "copyrighted",
    status: "available",
    href: "nineteeneightyfour/",
    accent: "#4a4a4a",
    summary: "In a totalitarian superstate ruled by Big Brother, Winston Smith commits the ultimate crime: thinking for himself.",
    why: "Surveillance, propaganda, and thought-control. Frequently challenged for its politics and its bleak — and endlessly relevant.",
  },
  {
    id: "animalfarm",
    title: "Animal Farm",
    author: "George Orwell",
    year: "1945",
    gradeBand: "9-12",
    grades: "8–12",
    themes: ["power", "history"],
    rights: "copyrighted",
    status: "available",
    href: "animalfarm/",
    accent: "#6a7a3a",
    summary: "Farm animals overthrow their farmer to build a society of equals — which slowly curdles into a new tyranny.",
    why: "An allegory of a revolution betrayed. Banned and challenged across the political spectrum for what it exposes about power.",
  },
  {
    id: "handmaidstale",
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    year: "1985",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["power", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "handmaidstale/",
    accent: "#7a1f2a",
    summary: "In a near-future theocracy, a woman is reduced to her fertility — and holds onto the memory of the freedom she lost.",
    why: "A dystopia of religious authoritarianism and control over women's bodies. Among the most-challenged books in America.",
  },
  {
    id: "lordoftheflies",
    title: "Lord of the Flies",
    author: "William Golding",
    year: "1954",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["power"],
    rights: "copyrighted",
    status: "available",
    href: "lordoftheflies/",
    accent: "#3a6a4a",
    summary: "Stranded on an island with no adults, a group of schoolboys builds a society that unravels into savagery.",
    why: "Long challenged for violence, bleakness, and language — a fixture of the canon about how thin the veneer of order can be.",
  },
  {
    id: "slaughterhouse",
    title: "Slaughterhouse-Five",
    author: "Kurt Vonnegut",
    year: "1969",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["power", "history"],
    rights: "copyrighted",
    status: "available",
    href: "slaughterhouse/",
    accent: "#5f6b7a",
    summary: "A dazed WWII veteran comes 'unstuck in time,' reliving the firebombing of Dresden and his abduction by aliens.",
    why: "Anti-war, absurd, and unflinching — one of the most-banned novels in America, once literally burned by a school board.",
  },

  /* ─────────────  Black experience & justice  ───────────── */
  {
    id: "colorpurple",
    title: "The Color Purple",
    author: "Alice Walker",
    year: "1982",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "colorpurple/",
    accent: "#6a3f8c",
    summary: "Told through letters, Celie survives abuse and hardship in the early-1900s South and slowly finds her voice, her sister, and love.",
    why: "A Pulitzer-winning novel of Black women's survival and self-discovery — banned for sexual content, abuse, and language.",
  },
  {
    id: "beloved",
    title: "Beloved",
    author: "Toni Morrison",
    year: "1987",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["history", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "beloved/",
    accent: "#7a1f2a",
    summary: "Years after escaping slavery, Sethe is haunted — literally — by the daughter she lost, and by a past that will not stay buried.",
    why: "A Nobel laureate's reckoning with the trauma of slavery. Frequently challenged for violence and disturbing content.",
  },
  {
    id: "raisininthesun",
    title: "A Raisin in the Sun",
    author: "Lorraine Hansberry",
    year: "1959",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "raisininthesun/",
    accent: "#c98a2b",
    summary: "A Black family in 1950s Chicago dreams of a better life — and clashes over what to do with a life-insurance check and a house in a white neighborhood.",
    why: "A landmark play on housing segregation, family, and dignity. Challenged over language and its portrayal of race.",
  },
  {
    id: "nativeson",
    title: "Native Son",
    author: "Richard Wright",
    year: "1940",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["justice", "power"],
    rights: "copyrighted",
    status: "available",
    href: "nativeson/",
    accent: "#4a4a4a",
    summary: "Bigger Thomas, a young Black man in 1930s Chicago, is trapped by poverty and racism into a spiral of fear and violence.",
    why: "A searing indictment of American racism. Frequently challenged for violence, language, and its unflinching view.",
  },
  {
    id: "longwaydown",
    title: "Long Way Down",
    author: "Jason Reynolds",
    year: "2017",
    gradeBand: "9-12",
    grades: "8–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "longwaydown/",
    accent: "#2a2a2a",
    summary: "In sixty seconds and a single elevator ride, Will decides whether to follow the rules and avenge his murdered brother.",
    why: "A verse novel on gun violence and the cycle of revenge — challenged over violence and language.",
  },
  {
    id: "dearmartin",
    title: "Dear Martin",
    author: "Nic Stone",
    year: "2017",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "dearmartin/",
    accent: "#2f5f9e",
    summary: "An Ivy-bound Black teen writes letters to Dr. King as he faces racial profiling, a police encounter, and a tragedy.",
    why: "A novel of policing, profiling, and code-switching — frequently challenged over race, violence, and language.",
  },
  {
    id: "monster",
    title: "Monster",
    author: "Walter Dean Myers",
    year: "1999",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice"],
    rights: "copyrighted",
    status: "available",
    href: "monster/",
    accent: "#3a3a3a",
    summary: "On trial for felony murder, sixteen-year-old Steve Harmon writes his life in jail as a screenplay to survive it.",
    why: "A novel of the juvenile justice system told as a film script — challenged over crime, language, and its subject.",
  },
  {
    id: "march",
    title: "March: Book One",
    author: "John Lewis, Andrew Aydin & Nate Powell",
    year: "2013",
    gradeBand: "9-12",
    grades: "8–12",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "march/",
    accent: "#b8231f",
    summary: "Congressman John Lewis's graphic memoir of his childhood and his path into the early civil-rights movement.",
    why: "A graphic memoir of the movement by one of its leaders — challenged despite, or because of, the history it tells.",
  },

  /* ─────────────  Identity & coming-of-age  ───────────── */
  {
    id: "melissa",
    title: "Melissa",
    author: "Alex Gino",
    year: "2015",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "melissa/",
    accent: "#d98a2b",
    summary: "A fourth-grader the world sees as a boy knows she is a girl — and, with a friend's help, finds a way to be seen.",
    why: "A warm story of a transgender kid (first published as 'George') — for years among the single most-banned books in America.",
  },
  {
    id: "speak",
    title: "Speak",
    author: "Laurie Halse Anderson",
    year: "1999",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "speak/",
    accent: "#4a6d8c",
    summary: "After a party the summer before high school, Melinda stops speaking — and slowly finds the words for what happened to her.",
    why: "A landmark novel about a sexual-assault survivor finding her voice — repeatedly challenged over its subject.",
  },
  {
    id: "poetx",
    title: "The Poet X",
    author: "Elizabeth Acevedo",
    year: "2018",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "poetx/",
    accent: "#7a1f5a",
    summary: "A Dominican-American teen in Harlem pours her body, her faith, and her anger into slam poetry.",
    why: "A verse novel on religion, body autonomy, and finding a voice — frequently challenged and pulled from shelves.",
  },
  {
    id: "perks",
    title: "The Perks of Being a Wallflower",
    author: "Stephen Chbosky",
    year: "1999",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "perks/",
    accent: "#6a5a8c",
    summary: "Through letters to a stranger, shy freshman Charlie navigates friendship, first love, trauma, and growing up.",
    why: "A coming-of-age story on mental health, abuse, and belonging — one of the most-banned books of its era.",
  },
  {
    id: "kiterunner",
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    year: "2003",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["history", "identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "kiterunner/",
    accent: "#3a6a8c",
    summary: "In Afghanistan and the America he flees to, Amir spends his life seeking redemption for betraying his childhood friend Hassan.",
    why: "A novel of friendship, guilt, and Afghan history — frequently challenged over a sexual-assault scene and language.",
  },
  {
    id: "ofmiceandmen",
    title: "Of Mice and Men",
    author: "John Steinbeck",
    year: "1937",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice"],
    rights: "copyrighted",
    status: "available",
    href: "ofmiceandmen/",
    accent: "#8a6a3a",
    summary: "Two migrant workers, George and Lennie, chase a fragile dream of a place of their own in Depression-era California.",
    why: "A tragedy of friendship, disability, and dignity — perennially among the most-challenged books for language and its ending.",
  },
  /* ─────────────  History & memory  ───────────── */
  {
    id: "thegiver",
    title: "The Giver",
    author: "Lois Lowry",
    year: "1993",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["power", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "thegiver/",
    accent: "#6a7a8c",
    summary: "In a 'perfect' community with no pain and no choices, twelve-year-old Jonas is chosen to receive the memories the world gave up.",
    why: "A dystopia that questions conformity, memory, and control — frequently challenged over euthanasia and its 'dark' themes.",
  },
  {
    id: "refugee",
    title: "Refugee",
    author: "Alan Gratz",
    year: "2017",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["history", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "refugee/",
    accent: "#2f6a8c",
    summary: "Three children — fleeing Nazi Germany, Castro's Cuba, and war-torn Syria — make desperate journeys toward safety across three eras.",
    why: "Three refugee stories braided across time — frequently challenged over violence, politics, and immigration.",
  },
  {
    id: "breadwinner",
    title: "The Breadwinner",
    author: "Deborah Ellis",
    year: "2000",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "history", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "breadwinner/",
    accent: "#8a5a2b",
    summary: "In Taliban-controlled Kabul, eleven-year-old Parvana disguises herself as a boy so she can move through the city and feed her family.",
    why: "A girl's survival under the Taliban — challenged over political and religious content.",
  },
  {
    id: "devilsarithmetic",
    title: "The Devil's Arithmetic",
    author: "Jane Yolen",
    year: "1988",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["history"],
    rights: "copyrighted",
    status: "available",
    href: "devilsarithmetic/",
    accent: "#6b6f76",
    summary: "A modern Jewish girl bored by 'remembering' is pulled back in time into a Nazi concentration camp, where memory becomes survival.",
    why: "A time-slip into the Holocaust that makes memory unforgettable — challenged over its intensity.",
  },
  {
    id: "chains",
    title: "Chains",
    author: "Laurie Halse Anderson",
    year: "2008",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "chains/",
    accent: "#4a6a4a",
    summary: "In Revolutionary-era New York, an enslaved girl named Isabel spies for a chance at the freedom the new nation promises everyone but her.",
    why: "Slavery during the American Revolution, told from the inside — challenged over violence and race.",
  },
  {
    id: "theycalledusenemy",
    title: "They Called Us Enemy",
    author: "George Takei",
    year: "2019",
    gradeBand: "9-12",
    grades: "8–12",
    themes: ["history", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "theycalledusenemy/",
    accent: "#b8231f",
    summary: "Actor George Takei's graphic memoir of his childhood imprisoned with his family in a WWII Japanese-American incarceration camp.",
    why: "A graphic memoir of the WWII incarceration — challenged for the very history it makes vivid.",
  },
  {
    id: "budnotbuddy",
    title: "Bud, Not Buddy",
    author: "Christopher Paul Curtis",
    year: "1999",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["history", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "budnotbuddy/",
    accent: "#c9822b",
    summary: "During the Great Depression, ten-year-old orphan Bud sets out across Michigan to find the father he's sure is a famous bandleader.",
    why: "A Depression-era search for family and belonging — challenged over language and content.",
  },
  {
    id: "bridgetoterabithia",
    title: "Bridge to Terabithia",
    author: "Katherine Paterson",
    year: "1977",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "bridgetoterabithia/",
    accent: "#3a7a6a",
    summary: "Two lonely kids invent a secret woodland kingdom called Terabithia — until a sudden tragedy changes everything.",
    why: "A tender story of friendship and grief — perennially challenged over death, language, and 'witchcraft.'",
  },

  /* ─────────────  Backlog — 100 more challenged titles  ───────────── */
  {
    id: "holes",
    title: "Holes",
    author: "Louis Sachar",
    year: "1998",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "holes/",
    accent: "#c47d2c",
    summary: "Wrongly convicted, Stanley Yelnats is sent to a brutal desert camp where boys dig holes all day, and he slowly uncovers the buried secret behind his family's supposed curse.",
    why: "Challenged over violence, a racially charged backstory, and depictions of cruelty at a juvenile detention camp.",
  },
  {
    id: "theoutsiders",
    title: "The Outsiders",
    author: "S. E. Hinton",
    year: "1967",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "theoutsiders/",
    accent: "#c9772f",
    summary: "In a divided town, working-class 'greaser' Ponyboy is caught in a deadly feud with the wealthy Socs, forcing him to confront loyalty, loss, and what really separates the two worlds.",
    why: "Challenged for gang violence, underage smoking and drinking, and strong language.",
  },
  {
    id: "tuckeverlasting",
    title: "Tuck Everlasting",
    author: "Natalie Babbitt",
    year: "1975",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "tuckeverlasting/",
    accent: "#4a7c59",
    summary: "A young girl discovers a family that drank from a spring granting eternal life, and must decide whether living forever is a gift or a burden.",
    why: "Challenged for its treatment of death and its questioning of religious ideas about immortality.",
  },
  {
    id: "wrinkleintime",
    title: "A Wrinkle in Time",
    author: "Madeleine L'Engle",
    year: "1962",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["power", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "wrinkleintime/",
    accent: "#3b3a8f",
    summary: "Meg Murry travels across space and time with her brother and a friend to rescue her scientist father from a dark force that is smothering free will across the universe.",
    why: "Challenged both for promoting the occult and, contradictorily, for its Christian references.",
  },
  {
    id: "lightningthief",
    title: "The Lightning Thief",
    author: "Rick Riordan",
    year: "2005",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "power"],
    rights: "copyrighted",
    status: "available",
    href: "lightningthief/",
    accent: "#4a5cd0",
    summary: "Percy Jackson learns he is the son of a Greek god and sets out on a cross-country quest to recover Zeus's stolen lightning bolt before war erupts among the Olympians.",
    why: "Challenged for its portrayal of the Greek gods and claims that it promotes paganism.",
  },
  {
    id: "harrypotter1",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J. K. Rowling",
    year: "1997",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "power"],
    rights: "copyrighted",
    status: "available",
    href: "harrypotter1/",
    accent: "#7a5a1e",
    summary: "An orphaned boy discovers he is a wizard, enrolls at Hogwarts, and uncovers a plot to steal a magical stone tied to the dark wizard who killed his parents.",
    why: "One of the most challenged books in the U.S., objected to for depicting witchcraft and magic.",
  },
  {
    id: "maniacmagee",
    title: "Maniac Magee",
    author: "Jerry Spinelli",
    year: "1990",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "maniacmagee/",
    accent: "#3a7d44",
    summary: "A homeless, legendary runaway boy crosses the racial dividing line of a small town, befriending families on both sides and quietly challenging its segregation.",
    why: "Challenged for its frank treatment of racism and racial slurs it depicts to confront prejudice.",
  },
  {
    id: "stargirl",
    title: "Stargirl",
    author: "Jerry Spinelli",
    year: "2000",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "stargirl/",
    accent: "#e0489b",
    summary: "A free-spirited new girl upends the conformity of an Arizona high school, and her fellow students must decide whether to embrace her or force her to fit in.",
    why: "Challenged over nonconformity themes and objections from some parents about its values.",
  },
  {
    id: "walktwomoons",
    title: "Walk Two Moons",
    author: "Sharon Creech",
    year: "1994",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "walktwomoons/",
    accent: "#3f7d5c",
    summary: "On a road trip with her grandparents, thirteen-year-old Sal tells a friend's story that mirrors her own, gradually facing the truth about her missing mother.",
    why: "Challenged for its handling of death, grief, and references to spiritual beliefs.",
  },
  {
    id: "blubber",
    title: "Blubber",
    author: "Judy Blume",
    year: "1974",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "blubber/",
    accent: "#3a6ea5",
    summary: "A fifth-grader joins in mercilessly bullying a heavyset classmate, then finds herself the target, in an unflinching look at cruelty and cowardice among kids.",
    why: "Challenged for bullying, profanity, and unpunished mean behavior among children.",
  },
  {
    id: "margaret",
    title: "Are You There God? It's Me, Margaret",
    author: "Judy Blume",
    year: "1970",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "margaret/",
    accent: "#c25a7c",
    summary: "As she moves to a new town, eleven-year-old Margaret navigates friendship, puberty, and her own private conversations with God about religion and growing up.",
    why: "Frequently challenged for candid discussion of puberty, menstruation, and religion.",
  },
  {
    id: "tigereyes",
    title: "Tiger Eyes",
    author: "Judy Blume",
    year: "1981",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "tigereyes/",
    accent: "#c2711f",
    summary: "After her father is killed in a robbery, Davey moves to New Mexico, where a new friendship helps her work through grief, fear, and the pull toward healing.",
    why: "Challenged for references to death, alcohol, and sexuality.",
  },
  {
    id: "freakthemighty",
    title: "Freak the Mighty",
    author: "Rodman Philbrick",
    year: "1993",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "freakthemighty/",
    accent: "#2f6f7e",
    summary: "A large, learning-disabled boy and a brilliant boy with a physical disability form an inseparable pair, combining their strengths to face bullies and a dark family secret.",
    why: "Challenged for violence, disturbing content, and offensive language.",
  },
  {
    id: "drama",
    title: "Drama",
    author: "Raina Telgemeier",
    year: "2012",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "drama/",
    accent: "#c0397e",
    summary: "A middle-school stage-crew member throws herself into the school musical while navigating crushes, friendships, and backstage drama.",
    why: "One of the most challenged books of the 2010s, objected to for LGBTQ characters and themes.",
  },
  {
    id: "smile",
    title: "Smile",
    author: "Raina Telgemeier",
    year: "2010",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "smile/",
    accent: "#e8607a",
    summary: "After a fall damages her front teeth, a sixth-grader endures years of dental work while navigating the ordinary humiliations of growing up.",
    why: "Challenged over depictions of insecurity, minor bullying, and its handling of adolescence.",
  },
  {
    id: "ghosttrack",
    title: "Ghost",
    author: "Jason Reynolds",
    year: "2016",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "ghosttrack/",
    accent: "#2f7d6b",
    summary: "A boy running from a traumatic past joins an elite track team, where a demanding coach helps him channel his speed and his anger into something better.",
    why: "Challenged for language, references to gun violence, and depictions of family trauma.",
  },
  {
    id: "outofmymind",
    title: "Out of My Mind",
    author: "Sharon M. Draper",
    year: "2010",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "outofmymind/",
    accent: "#6a4bb0",
    summary: "A brilliant girl with cerebral palsy who cannot speak finally gets a device to share her thoughts, forcing her school to see past her disability.",
    why: "Challenged over its portrayal of disability and claims that it makes readers uncomfortable.",
  },
  {
    id: "islandbluedolphins",
    title: "Island of the Blue Dolphins",
    author: "Scott O'Dell",
    year: "1960",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "islandbluedolphins/",
    accent: "#1f7a8c",
    summary: "Stranded alone for years on a Pacific island, a young Native girl survives by her own skill and courage while waiting for rescue.",
    why: "Challenged for violence and for its depiction of the killing of animals.",
  },
  {
    id: "mybrothersam",
    title: "My Brother Sam Is Dead",
    author: "James Lincoln Collier and Christopher Collier",
    year: "1974",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["history", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "mybrothersam/",
    accent: "#3a5a7a",
    summary: "During the Revolutionary War, a boy is torn between his Loyalist father and his rebel older brother, learning that war offers no clean heroes.",
    why: "Frequently challenged for violence, profanity, and depictions of the brutality of war.",
  },
  {
    id: "thecay",
    title: "The Cay",
    author: "Theodore Taylor",
    year: "1969",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "thecay/",
    accent: "#0e7c86",
    summary: "Blinded and shipwrecked on a tiny island, a prejudiced white boy is kept alive by an older Black man, and his assumptions dissolve as they depend on each other.",
    why: "Challenged over its handling of race and dialect and debates about racial stereotypes.",
  },
  {
    id: "sounder",
    title: "Sounder",
    author: "William H. Armstrong",
    year: "1969",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "sounder/",
    accent: "#6b4a2b",
    summary: "A poor Black sharecropping family in the South is shattered when the father is jailed for stealing food, and a boy holds on to hope through his loyal dog.",
    why: "Challenged for racial content and criticized over its depiction of a Black family.",
  },
  {
    id: "witchblackbird",
    title: "The Witch of Blackbird Pond",
    author: "Elizabeth George Speare",
    year: "1958",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "witchblackbird/",
    accent: "#3a5a7d",
    summary: "A spirited girl arrives in Puritan Connecticut, befriends a lonely old woman rumored to be a witch, and is soon accused of witchcraft herself.",
    why: "Challenged for its references to witchcraft and depiction of Puritan intolerance.",
  },
  {
    id: "whenyoureachme",
    title: "When You Reach Me",
    author: "Rebecca Stead",
    year: "2009",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "whenyoureachme/",
    accent: "#3f6db0",
    summary: "A New York sixth-grader receives mysterious notes that seem to predict the future, drawing her into a puzzle that ties friendship, time, and fate together.",
    why: "Challenged over occasional language and mature situations for its age group.",
  },
  {
    id: "warthatsavedme",
    title: "The War That Saved My Life",
    author: "Kimberly Brubaker Bradley",
    year: "2015",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["history", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "warthatsavedme/",
    accent: "#4a6b8a",
    summary: "Evacuated from wartime London by an abusive mother, a disabled girl and her brother find unexpected freedom and care in the English countryside.",
    why: "Challenged for depictions of child abuse and difficult family situations.",
  },
  {
    id: "fever1793",
    title: "Fever 1793",
    author: "Laurie Halse Anderson",
    year: "2000",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["history", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "fever1793/",
    accent: "#a83232",
    summary: "As yellow fever ravages Philadelphia, a teenage girl loses her sheltered life and must survive, mature, and hold her family together amid the epidemic.",
    why: "Challenged for graphic depictions of illness, death, and disturbing historical detail.",
  },
  {
    id: "longwaytowater",
    title: "A Long Walk to Water",
    author: "Linda Sue Park",
    year: "2010",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "longwaytowater/",
    accent: "#c8772b",
    summary: "Two Sudanese lives braid together across decades: a boy fleeing civil war as a 'lost boy' and a girl whose village survives by walking hours for water.",
    why: "Challenged for depictions of war violence and its portrayal of hardship in Sudan.",
  },
  {
    id: "frontdesk",
    title: "Front Desk",
    author: "Kelly Yang",
    year: "2018",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "frontdesk/",
    accent: "#e0592a",
    summary: "An immigrant girl runs the front desk of the motel her parents manage, hiding struggling newcomers and standing up to a bullying owner.",
    why: "Challenged over its depiction of racism, immigration, and economic hardship.",
  },
  {
    id: "amalunbound",
    title: "Amal Unbound",
    author: "Aisha Saeed",
    year: "2018",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "amalunbound/",
    accent: "#c77c2e",
    summary: "A Pakistani girl who dreams of becoming a teacher is forced into indentured servitude for a powerful landlord, and quietly plots to reclaim her future.",
    why: "Challenged over depictions of servitude, class oppression, and cultural content.",
  },
  {
    id: "mercisuarez",
    title: "Merci Suárez Changes Gears",
    author: "Meg Medina",
    year: "2018",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "mercisuarez/",
    accent: "#e0607e",
    summary: "A Cuban American scholarship student juggles school, family duties, and her grandfather's declining health as she figures out who she is.",
    why: "Challenged over cultural content and its handling of family and illness.",
  },
  {
    id: "skinimin",
    title: "The Skin I'm In",
    author: "Sharon G. Flake",
    year: "1998",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "skinimin/",
    accent: "#7b3f6b",
    summary: "Teased for her dark skin, a middle-schooler finds her voice through a challenging new teacher and learns to define her own worth.",
    why: "Challenged for language, bullying, and its frank treatment of colorism.",
  },
  {
    id: "crash",
    title: "Crash",
    author: "Jerry Spinelli",
    year: "1996",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "crash/",
    accent: "#d4562a",
    summary: "A cocky football star who bullies a pacifist Quaker classmate slowly changes when family crisis forces him to reconsider who he wants to be.",
    why: "Challenged for bullying, language, and its depictions of aggressive behavior.",
  },
  {
    id: "hoot",
    title: "Hoot",
    author: "Carl Hiaasen",
    year: "2002",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice"],
    rights: "copyrighted",
    status: "available",
    href: "hoot/",
    accent: "#2f8f5a",
    summary: "A new kid in Florida joins a scrappy effort to stop a pancake-house construction site from destroying a colony of burrowing owls.",
    why: "Challenged for language, bullying, and its portrayal of rule-breaking activism.",
  },
  {
    id: "blended",
    title: "Blended",
    author: "Sharon M. Draper",
    year: "2018",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "blended/",
    accent: "#7a5aae",
    summary: "A biracial girl split between her divorced parents' homes navigates identity and family tension amid an incident of racial bias at her school.",
    why: "Challenged over its treatment of race, divorce, and a racially charged incident.",
  },
  {
    id: "efrendivided",
    title: "Efrén Divided",
    author: "Ernesto Cisneros",
    year: "2020",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "efrendivided/",
    accent: "#c94f2e",
    summary: "When his undocumented mother is deported, a boy must care for his younger siblings and cross the border to try to bring her home.",
    why: "Challenged over its depiction of immigration and deportation.",
  },
  {
    id: "seedfolks",
    title: "Seedfolks",
    author: "Paul Fleischman",
    year: "1997",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "seedfolks/",
    accent: "#4a8f3a",
    summary: "One by one, neighbors of many backgrounds transform a trash-filled city lot into a community garden, and into a community.",
    why: "Challenged over depictions of poverty, ethnic tension, and neighborhood crime.",
  },
  {
    id: "flowersforalgernon",
    title: "Flowers for Algernon",
    author: "Daniel Keyes",
    year: "1966",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "flowersforalgernon/",
    accent: "#5a6b8c",
    summary: "An experimental surgery makes an intellectually disabled man a genius, but as his intelligence peaks he realizes the change may not last.",
    why: "Frequently challenged for sexual content and its treatment of disability.",
  },
  {
    id: "thehobbit",
    title: "The Hobbit",
    author: "J. R. R. Tolkien",
    year: "1937",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "power"],
    rights: "copyrighted",
    status: "available",
    href: "thehobbit/",
    accent: "#4a6a3a",
    summary: "A comfort-loving hobbit is swept into a quest with dwarves to reclaim a treasure guarded by a dragon, discovering courage he never knew he had.",
    why: "Challenged for fantasy violence and claims that its magic promotes the occult.",
  },
  {
    id: "tangerine",
    title: "Tangerine",
    author: "Edward Bloor",
    year: "1997",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "tangerine/",
    accent: "#d98a2b",
    summary: "A legally blind boy who loves soccer uncovers dark family secrets and buried truths in a strange Florida town built beside a smoldering muck fire.",
    why: "Challenged for violence, language, and depictions of a dysfunctional family.",
  },
  {
    id: "catcherintherye",
    title: "The Catcher in the Rye",
    author: "J. D. Salinger",
    year: "1951",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "catcherintherye/",
    accent: "#a12f2f",
    summary: "Expelled from prep school, a disillusioned teenager wanders New York City for a few days, railing against a world he finds phony while quietly falling apart.",
    why: "One of the most challenged American novels, cited for profanity, sexuality, and rebellion.",
  },
  {
    id: "grapesofwrath",
    title: "The Grapes of Wrath",
    author: "John Steinbeck",
    year: "1939",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "grapesofwrath/",
    accent: "#c17a2f",
    summary: "Driven off their Dust Bowl farm, the Joad family migrates to California seeking work and dignity, only to meet exploitation and hardship.",
    why: "Challenged and once banned for profanity, sexual content, and its critique of capitalism.",
  },
  {
    id: "chocolatewar",
    title: "The Chocolate War",
    author: "Robert Cormier",
    year: "1974",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["power", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "chocolatewar/",
    accent: "#6b3f28",
    summary: "A Catholic high-schooler who refuses to sell fundraising chocolates becomes the target of a secret society and a manipulative teacher.",
    why: "Frequently challenged for violence, profanity, sexual content, and a bleak worldview.",
  },
  {
    id: "iamthecheese",
    title: "I Am the Cheese",
    author: "Robert Cormier",
    year: "1977",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["power", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "iamthecheese/",
    accent: "#3f5a6e",
    summary: "A boy bicycling to visit his father recounts fragments of memory that slowly reveal a chilling conspiracy and the truth about his family.",
    why: "Challenged for disturbing content and its treatment of government conspiracy and violence.",
  },
  {
    id: "separatepeace",
    title: "A Separate Peace",
    author: "John Knowles",
    year: "1959",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "separatepeace/",
    accent: "#3f6b7a",
    summary: "At a New England prep school during World War II, a boy's intense friendship curdles into jealousy, leading to an act with lifelong consequences.",
    why: "Challenged for profanity and perceived homosexual undertones.",
  },
  {
    id: "thousandsplendidsuns",
    title: "A Thousand Splendid Suns",
    author: "Khaled Hosseini",
    year: "2007",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "thousandsplendidsuns/",
    accent: "#c77d2a",
    summary: "Across decades of Afghan war and oppression, two women bound to the same abusive husband forge a fierce, sustaining friendship.",
    why: "Challenged for depictions of abuse, sexual violence, and mature content.",
  },
  {
    id: "songofsolomon",
    title: "Song of Solomon",
    author: "Toni Morrison",
    year: "1977",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "songofsolomon/",
    accent: "#7a5c3a",
    summary: "A Black man called Milkman journeys from Michigan to the South to trace his family's roots and, with them, a buried inheritance of flight and freedom.",
    why: "Frequently challenged for sexual content, violence, and strong language.",
  },
  {
    id: "invisibleman",
    title: "Invisible Man",
    author: "Ralph Ellison",
    year: "1952",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "invisibleman/",
    accent: "#c8961e",
    summary: "An unnamed Black narrator recounts his journey through a America that refuses to see him, from the segregated South to the currents of Harlem.",
    why: "Challenged for language, sexual content, and violence.",
  },
  {
    id: "blackboy",
    title: "Black Boy",
    author: "Richard Wright",
    year: "1945",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "blackboy/",
    accent: "#9a6a2a",
    summary: "Wright's memoir of growing up Black and poor in the Jim Crow South, and of the hunger for words and freedom that drove him north.",
    why: "Frequently challenged for profanity, violence, and its unflinching depiction of racism.",
  },
  {
    id: "gotellit",
    title: "Go Tell It on the Mountain",
    author: "James Baldwin",
    year: "1953",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "gotellit/",
    accent: "#c78a2b",
    summary: "On his fourteenth birthday in 1930s Harlem, a boy wrestles with faith, family, and his stern preacher stepfather in a single searching day.",
    why: "Challenged for sexual content, language, and its treatment of religion.",
  },
  {
    id: "bealestreet",
    title: "If Beale Street Could Talk",
    author: "James Baldwin",
    year: "1974",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "bealestreet/",
    accent: "#c07b2a",
    summary: "A young Harlem woman fights to prove her wrongly imprisoned fiancé's innocence as she carries their child, sustained by love and family.",
    why: "Challenged for sexual content, profanity, and depictions of injustice.",
  },
  {
    id: "betweentheworld",
    title: "Between the World and Me",
    author: "Ta-Nehisi Coates",
    year: "2015",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "betweentheworld/",
    accent: "#2b4a7e",
    summary: "Written as a letter to his teenage son, Coates reckons with what it means to inhabit a Black body in America and how history lives in the present.",
    why: "Challenged as divisive and for language and its critique of race in America.",
  },
  {
    id: "newjimcrow",
    title: "The New Jim Crow",
    author: "Michelle Alexander",
    year: "2010",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["justice", "power"],
    rights: "copyrighted",
    status: "available",
    href: "newjimcrow/",
    accent: "#3b4a63",
    summary: "Alexander argues that mass incarceration functions as a modern system of racial control, replacing the old caste lines of Jim Crow.",
    why: "Challenged as politically divisive and for its critique of the justice system.",
  },
  {
    id: "malcolmx",
    title: "The Autobiography of Malcolm X",
    author: "Malcolm X and Alex Haley",
    year: "1965",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "malcolmx/",
    accent: "#3a4a8c",
    summary: "The life story of Malcolm X, from a troubled youth through prison and conversion to his rise as a fierce voice for Black liberation.",
    why: "Frequently challenged for language, violence, and its militant political views.",
  },
  {
    id: "lessonbeforedying",
    title: "A Lesson Before Dying",
    author: "Ernest J. Gaines",
    year: "1993",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "lessonbeforedying/",
    accent: "#3f5a7a",
    summary: "In 1940s Louisiana, a teacher is asked to help a wrongly condemned young Black man face his execution with dignity, and both men are changed.",
    why: "Challenged for language, violence, and its treatment of race and capital punishment.",
  },
  {
    id: "tomsawyer",
    title: "The Adventures of Tom Sawyer",
    author: "Mark Twain",
    year: "1876",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "history"],
    rights: "public-domain",
    status: "available",
    href: "tomsawyer/",
    accent: "#3a7d5c",
    summary: "A mischievous boy in a Mississippi River town skips school, hunts treasure, and stumbles into danger after witnessing a graveyard murder.",
    why: "Challenged for racial slurs, dialect, and its depiction of race in the antebellum South.",
  },
  {
    id: "scarletletter",
    title: "The Scarlet Letter",
    author: "Nathaniel Hawthorne",
    year: "1850",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "public-domain",
    status: "available",
    href: "scarletletter/",
    accent: "#a01f2e",
    summary: "In Puritan Boston, a woman branded for adultery raises her daughter alone while the town hunts for the father who will not confess.",
    why: "Challenged over its treatment of adultery and its critique of religious hypocrisy.",
  },
  {
    id: "theawakening",
    title: "The Awakening",
    author: "Kate Chopin",
    year: "1899",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity"],
    rights: "public-domain",
    status: "available",
    href: "theawakening/",
    accent: "#2f7d8c",
    summary: "A Louisiana wife and mother awakens to her own desires and independence, straining against the roles her society allows her.",
    why: "Long challenged for its frank treatment of female sexuality and marital dissatisfaction.",
  },
  {
    id: "greatgatsby",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    year: "1925",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "power"],
    rights: "public-domain",
    status: "available",
    href: "greatgatsby/",
    accent: "#c9a227",
    summary: "A mysterious millionaire throws lavish parties to win back a lost love, in a glittering Jazz-Age tragedy of wealth, longing, and illusion.",
    why: "Challenged for language, sexual references, and depictions of drinking and adultery.",
  },
  {
    id: "farewelltoarms",
    title: "A Farewell to Arms",
    author: "Ernest Hemingway",
    year: "1929",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "farewelltoarms/",
    accent: "#4a6274",
    summary: "An American ambulance driver on the Italian front in World War I falls in love with a nurse, and the two try to escape the war together.",
    why: "Challenged and once banned for sexual content, profanity, and its bleak view of war.",
  },
  {
    id: "catch22",
    title: "Catch-22",
    author: "Joseph Heller",
    year: "1961",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["power", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "catch22/",
    accent: "#6b6f3a",
    summary: "A World War II bombardier tries to stay alive amid absurd military bureaucracy, trapped by a rule that makes escape impossible.",
    why: "Challenged for profanity, sexual content, and its irreverent satire of war and authority.",
  },
  {
    id: "cuckoosnest",
    title: "One Flew Over the Cuckoo's Nest",
    author: "Ken Kesey",
    year: "1962",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["power", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "cuckoosnest/",
    accent: "#5a7d6e",
    summary: "A boisterous new patient challenges the iron rule of a psychiatric ward's head nurse, sparking a battle over freedom and control.",
    why: "Frequently challenged for language, sexual content, violence, and its treatment of mental illness.",
  },
  {
    id: "clockworkorange",
    title: "A Clockwork Orange",
    author: "Anthony Burgess",
    year: "1962",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["power", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "clockworkorange/",
    accent: "#d1561f",
    summary: "A violent young delinquent in a near-future England is subjected to an experimental treatment that strips away his free will.",
    why: "Challenged for extreme violence, sexual content, and disturbing language.",
  },
  {
    id: "catscradle",
    title: "Cat's Cradle",
    author: "Kurt Vonnegut",
    year: "1963",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["power"],
    rights: "copyrighted",
    status: "available",
    href: "catscradle/",
    accent: "#2f6d8c",
    summary: "A satirical tale following a doomsday substance and an invented religion toward the possible end of the world.",
    why: "Challenged for its irreverent treatment of religion, science, and language.",
  },
  {
    id: "thecrucible",
    title: "The Crucible",
    author: "Arthur Miller",
    year: "1953",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "power"],
    rights: "copyrighted",
    status: "available",
    href: "thecrucible/",
    accent: "#7a2b2b",
    summary: "In Salem, a wave of witchcraft accusations spirals into deadly hysteria, in a drama that mirrors the fear of the McCarthy era.",
    why: "Challenged for its treatment of witchcraft, sexuality, and its political allegory.",
  },
  {
    id: "streetcar",
    title: "A Streetcar Named Desire",
    author: "Tennessee Williams",
    year: "1947",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["identity", "power"],
    rights: "copyrighted",
    status: "available",
    href: "streetcar/",
    accent: "#4a7a8c",
    summary: "A fading Southern belle moves in with her sister in New Orleans, where her fragile illusions collide with her brutish brother-in-law.",
    why: "Challenged for sexual content, violence, and its depiction of assault and mental decline.",
  },
  {
    id: "glassmenagerie",
    title: "The Glass Menagerie",
    author: "Tennessee Williams",
    year: "1944",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "glassmenagerie/",
    accent: "#7a5a86",
    summary: "A restless son, his fragile sister, and their domineering mother cling to memory and illusion in a cramped St. Louis apartment.",
    why: "Challenged over mature themes and its treatment of family dysfunction and disability.",
  },
  {
    id: "deathofsalesman",
    title: "Death of a Salesman",
    author: "Arthur Miller",
    year: "1949",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "power"],
    rights: "copyrighted",
    status: "available",
    href: "deathofsalesman/",
    accent: "#8a6d3b",
    summary: "An aging salesman clinging to the American Dream unravels as his career and his relationship with his sons collapse.",
    why: "Challenged for language and its critique of American values and depictions of infidelity.",
  },
  {
    id: "fences",
    title: "Fences",
    author: "August Wilson",
    year: "1985",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "fences/",
    accent: "#7a5230",
    summary: "A former Negro-league ballplayer turned garbageman in 1950s Pittsburgh wrestles with pride, betrayal, and the dreams he denies his son.",
    why: "Challenged for language and its treatment of race, infidelity, and family conflict.",
  },
  {
    id: "funhome",
    title: "Fun Home",
    author: "Alison Bechdel",
    year: "2006",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "funhome/",
    accent: "#2f6d68",
    summary: "In this graphic memoir, Bechdel traces her coming out and her relationship with her closeted father, who ran the family funeral home.",
    why: "Frequently challenged for its LGBTQ content and graphic depictions of sexuality.",
  },
  {
    id: "thebookthief",
    title: "The Book Thief",
    author: "Markus Zusak",
    year: "2005",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "thebookthief/",
    accent: "#4a5568",
    summary: "Narrated by Death, the story of a German girl in Nazi Germany who steals books and shares them while her family hides a Jewish man.",
    why: "Challenged for language, violence, and its depiction of the Holocaust.",
  },
  {
    id: "allquiet",
    title: "All Quiet on the Western Front",
    author: "Erich Maria Remarque",
    year: "1929",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "allquiet/",
    accent: "#6b7043",
    summary: "A young German soldier's account of the horror, camaraderie, and disillusionment of the trenches in World War I.",
    why: "Banned by the Nazis and elsewhere challenged for graphic violence and anti-war content.",
  },
  {
    id: "whenemperordivine",
    title: "When the Emperor Was Divine",
    author: "Julie Otsuka",
    year: "2002",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "whenemperordivine/",
    accent: "#a86b3c",
    summary: "A Japanese American family is uprooted from their California home and interned during World War II, told through their quiet, aching perspectives.",
    why: "Challenged over its treatment of internment, racism, and difficult history.",
  },
  {
    id: "longwaygone",
    title: "A Long Way Gone",
    author: "Ishmael Beah",
    year: "2007",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "longwaygone/",
    accent: "#8a5a2b",
    summary: "Beah's memoir of being forced into war as a child soldier in Sierra Leone, and of his long road to rehabilitation and recovery.",
    why: "Challenged for graphic violence, drug use, and disturbing war content.",
  },
  {
    id: "iammalala",
    title: "I Am Malala",
    author: "Malala Yousafzai and Christina Lamb",
    year: "2013",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "iammalala/",
    accent: "#c0286a",
    summary: "The memoir of the Pakistani girl who defied the Taliban's ban on girls' education and survived an assassination attempt to become a global advocate.",
    why: "Challenged in some places over religious content and its politics around Islam and the Taliban.",
  },
  {
    id: "purplehibiscus",
    title: "Purple Hibiscus",
    author: "Chimamanda Ngozi Adichie",
    year: "2003",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "power"],
    rights: "copyrighted",
    status: "available",
    href: "purplehibiscus/",
    accent: "#7d3c98",
    summary: "A Nigerian girl living under her devout, abusive father begins to find her voice during a stay with her free-spirited aunt.",
    why: "Challenged for depictions of domestic abuse, religious extremism, and violence.",
  },
  {
    id: "halfyellowsun",
    title: "Half of a Yellow Sun",
    author: "Chimamanda Ngozi Adichie",
    year: "2006",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["history", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "halfyellowsun/",
    accent: "#c79a2e",
    summary: "The lives of several characters intertwine amid the Nigerian-Biafran War, tracing love and loss against the collapse of a would-be nation.",
    why: "Challenged for sexual content, violence, and graphic depictions of war.",
  },
  {
    id: "thingsfallapart",
    title: "Things Fall Apart",
    author: "Chinua Achebe",
    year: "1958",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "thingsfallapart/",
    accent: "#a0522d",
    summary: "A proud Igbo leader in precolonial Nigeria watches his world unravel as British colonizers and missionaries arrive.",
    why: "Challenged for violence, its depiction of colonialism, and religious content.",
  },
  {
    id: "crybelovedcountry",
    title: "Cry, the Beloved Country",
    author: "Alan Paton",
    year: "1948",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "crybelovedcountry/",
    accent: "#2f6b46",
    summary: "A rural Black pastor journeys to Johannesburg to find his son, confronting the injustices of a South Africa on the edge of apartheid.",
    why: "Challenged over its treatment of race, violence, and the politics of apartheid.",
  },
  {
    id: "houseofspirits",
    title: "The House of the Spirits",
    author: "Isabel Allende",
    year: "1982",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["power", "history"],
    rights: "copyrighted",
    status: "available",
    href: "houseofspirits/",
    accent: "#7a2f3a",
    summary: "Four generations of a Latin American family live through love, magic, and political upheaval that leads to a violent dictatorship.",
    why: "Challenged for sexual content, violence, and political themes.",
  },
  {
    id: "hundredyears",
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    year: "1967",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["history", "power"],
    rights: "copyrighted",
    status: "available",
    href: "hundredyears/",
    accent: "#c99a2e",
    summary: "The rise and fall of the Buendía family across seven generations in the mythical town of Macondo, in a landmark of magical realism.",
    why: "Challenged for sexual content and its magical, unconventional storytelling.",
  },
  {
    id: "likewaterchocolate",
    title: "Like Water for Chocolate",
    author: "Laura Esquivel",
    year: "1989",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["identity", "power"],
    rights: "copyrighted",
    status: "available",
    href: "likewaterchocolate/",
    accent: "#a83250",
    summary: "Forbidden to marry, a young Mexican woman pours her longing into her cooking, which magically transmits her emotions to those who eat it.",
    why: "Challenged for sexual content and mature themes.",
  },
  {
    id: "thealchemist",
    title: "The Alchemist",
    author: "Paulo Coelho",
    year: "1988",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "thealchemist/",
    accent: "#c68a1e",
    summary: "A Spanish shepherd boy follows a recurring dream across North Africa in search of treasure, learning to listen to his heart along the way.",
    why: "Challenged over its religious and spiritual content.",
  },
  {
    id: "thejungle",
    title: "The Jungle",
    author: "Upton Sinclair",
    year: "1906",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["justice", "power"],
    rights: "public-domain",
    status: "available",
    href: "thejungle/",
    accent: "#8a3b2a",
    summary: "A Lithuanian immigrant family is ground down by the brutal conditions of Chicago's meatpacking industry in the early 1900s.",
    why: "Challenged and once banned for its graphic content and socialist politics.",
  },
  {
    id: "onedayivan",
    title: "One Day in the Life of Ivan Denisovich",
    author: "Aleksandr Solzhenitsyn",
    year: "1962",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["power", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "onedayivan/",
    accent: "#4a5a6a",
    summary: "A single ordinary day of a prisoner in a Soviet labor camp, tracing his small victories in the fight to keep his dignity.",
    why: "Banned in the Soviet Union and challenged elsewhere for its bleak political content.",
  },
  {
    id: "thepearl",
    title: "The Pearl",
    author: "John Steinbeck",
    year: "1947",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "power"],
    rights: "copyrighted",
    status: "available",
    href: "thepearl/",
    accent: "#127a8a",
    summary: "A poor Mexican pearl diver finds an enormous pearl that promises a better life but instead brings greed, violence, and ruin.",
    why: "Challenged for violence and its bleak view of poverty and greed.",
  },
  {
    id: "easteden",
    title: "East of Eden",
    author: "John Steinbeck",
    year: "1952",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "easteden/",
    accent: "#c08a2d",
    summary: "Two families in California's Salinas Valley reenact the story of Cain and Abel across generations, wrestling with love, rejection, and free will.",
    why: "Challenged for sexual content, violence, and language.",
  },
  {
    id: "thebelljar",
    title: "The Bell Jar",
    author: "Sylvia Plath",
    year: "1963",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "thebelljar/",
    accent: "#3a7d7b",
    summary: "A talented young woman interning in New York spirals into depression, tracing her descent and struggle toward recovery.",
    why: "Challenged for its depictions of mental illness, suicide, and sexuality.",
  },
  {
    id: "thingstheycarried",
    title: "The Things They Carried",
    author: "Tim O'Brien",
    year: "1990",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["history", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "thingstheycarried/",
    accent: "#5a5f2e",
    summary: "Linked stories about a platoon of American soldiers in Vietnam, weighing the physical and emotional burdens they carried through the war.",
    why: "Challenged for profanity, graphic violence, and sexual content.",
  },
  {
    id: "blessmeultima",
    title: "Bless Me, Ultima",
    author: "Rudolfo Anaya",
    year: "1972",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "blessmeultima/",
    accent: "#c07a1e",
    summary: "In 1940s New Mexico, a boy comes of age under the guidance of a curandera healer, balancing his family's faith with older folk traditions.",
    why: "Frequently challenged for language, violence, and depictions of folk spirituality.",
  },
  {
    id: "womanwarrior",
    title: "The Woman Warrior",
    author: "Maxine Hong Kingston",
    year: "1976",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "womanwarrior/",
    accent: "#3f7d74",
    summary: "Blending memoir and Chinese myth, Kingston explores growing up Chinese American through the stories of the women in her family.",
    why: "Challenged over sexual content, violence, and its blend of myth and memoir.",
  },
  {
    id: "joyluckclub",
    title: "The Joy Luck Club",
    author: "Amy Tan",
    year: "1989",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "joyluckclub/",
    accent: "#2f7d6b",
    summary: "Four Chinese immigrant mothers and their American-born daughters trade interlocking stories of heritage, sacrifice, and misunderstanding.",
    why: "Challenged for sexual content, violence, and mature themes.",
  },
  {
    id: "bastardcarolina",
    title: "Bastard Out of Carolina",
    author: "Dorothy Allison",
    year: "1992",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "bastardcarolina/",
    accent: "#8a4b5c",
    summary: "A poor South Carolina girl endures poverty and a violent stepfather, holding on to her fierce sense of self.",
    why: "Frequently challenged for graphic depictions of child abuse and sexual violence.",
  },
  {
    id: "crank",
    title: "Crank",
    author: "Ellen Hopkins",
    year: "2004",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "crank/",
    accent: "#7a2e46",
    summary: "Told in verse, a good student's life unravels after she becomes addicted to crystal meth, based on the author's own daughter's story.",
    why: "One of the most challenged books, cited for drug use, sexual content, and profanity.",
  },
  {
    id: "goaskalice",
    title: "Go Ask Alice",
    author: "Anonymous",
    year: "1971",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "goaskalice/",
    accent: "#6a4a8f",
    summary: "Presented as a teenage girl's diary, this cautionary tale follows her slide into drug addiction and life on the streets.",
    why: "Frequently challenged for drug use, sexual content, and profanity.",
  },
  {
    id: "thirteenreasons",
    title: "Thirteen Reasons Why",
    author: "Jay Asher",
    year: "2007",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "thirteenreasons/",
    accent: "#3a7d8c",
    summary: "A boy receives a set of tapes recorded by a classmate who died by suicide, each explaining one reason that led to her decision.",
    why: "Frequently challenged for its depiction of suicide, sexual assault, and mature content.",
  },
  {
    id: "lookingforalaska",
    title: "Looking for Alaska",
    author: "John Green",
    year: "2005",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "lookingforalaska/",
    accent: "#3a5a8c",
    summary: "At a boarding school, a boy falls for the magnetic, self-destructive Alaska, and must reckon with a sudden tragedy and its aftermath.",
    why: "One of the most challenged books, cited for sexual content, language, and drug use.",
  },
  {
    id: "faultinstars",
    title: "The Fault in Our Stars",
    author: "John Green",
    year: "2012",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "faultinstars/",
    accent: "#2e6b8f",
    summary: "Two teenagers who meet at a cancer support group fall in love and travel to Amsterdam, facing illness and mortality with wit and honesty.",
    why: "Challenged for language, sexual content, and its treatment of illness and death.",
  },
  {
    id: "eleanorpark",
    title: "Eleanor & Park",
    author: "Rainbow Rowell",
    year: "2013",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "eleanorpark/",
    accent: "#c0455f",
    summary: "Two misfit teenagers bond over comics and mixtapes on the school bus in 1980s Omaha, building a first love against difficult home lives.",
    why: "Frequently challenged for profanity and sexual references.",
  },
  {
    id: "forever",
    title: "Forever",
    author: "Judy Blume",
    year: "1975",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["identity"],
    rights: "copyrighted",
    status: "available",
    href: "forever/",
    accent: "#c94f7c",
    summary: "Two high-school seniors fall in love and navigate their first serious relationship, including their decision to become sexually involved.",
    why: "Frequently challenged for its frank depiction of teenage sexuality.",
  },
  {
    id: "the57bus",
    title: "The 57 Bus",
    author: "Dashka Slater",
    year: "2017",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "the57bus/",
    accent: "#c8621a",
    summary: "A true account of two Oakland teens whose lives collide when one sets the other's skirt on fire on a city bus, and the fallout that follows.",
    why: "Challenged for LGBTQ content, its discussion of gender, and depictions of violence.",
  },
  {
    id: "concreterose",
    title: "Concrete Rose",
    author: "Angie Thomas",
    year: "2021",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "concreterose/",
    accent: "#c0396b",
    summary: "A teenage boy in a tough neighborhood becomes a young father and struggles to leave gang life behind and define his own manhood.",
    why: "Challenged for profanity, drug references, and depictions of gang violence.",
  },
  {
    id: "notesmidnightdriver", title: "Notes from the Midnight Driver", author: "Jordan Sonnenblick", year: "2006",
    gradeBand: "9-12", grades: "9–10", themes: ["identity"], rights: "copyrighted", status: "available", href: "notesmidnightdriver/", accent: "#754c78",
    summary: "Court-ordered service pairs a teenager with a sharp-tongued older jazz musician, turning punishment into a difficult education in accountability, grief, and friendship.",
    why: "A CCHS 2026 required summer-reading title; this quotation-free room requires lawful access to the novel.",
  },
  {
    id: "oldmansea", title: "The Old Man and the Sea", author: "Ernest Hemingway", year: "1952",
    gradeBand: "9-12", grades: "9–12", themes: ["identity", "power"], rights: "copyrighted", status: "available", href: "oldmansea/", accent: "#376b78",
    summary: "An aging Cuban fisherman’s struggle with a great marlin tests endurance, dignity, respect for nature, and the meaning of defeat.",
    why: "A CCHS 2026 required summer-reading title; still copyrighted in the United States.",
  },
  {
    id: "blackships", title: "Black Ships Before Troy: The Story of the Iliad", author: "Rosemary Sutcliff", year: "1993",
    gradeBand: "9-12", grades: "9–10", themes: ["history", "power"], rights: "copyrighted", status: "available", href: "blackships/", accent: "#8c5d2f",
    summary: "A continuous retelling of the Trojan War that places Achilles, Hector, fate, honor, grief, and war’s human cost in one mythic arc.",
    why: "Required for CCHS English II Honors and AP Seminar; the modern retelling is copyrighted.",
  },
  {
    id: "boywhoharnessed", title: "The Boy Who Harnessed the Wind (Young Readers Edition)", author: "William Kamkwamba and Bryan Mealer", year: "2015",
    gradeBand: "9-12", grades: "9–10", themes: ["justice", "identity"], rights: "copyrighted", status: "available", href: "boywhoharnessed/", accent: "#4f7b42",
    summary: "A Malawian teenager draws on library science, scrap materials, and iterative engineering to build a windmill amid famine and interrupted schooling.",
    why: "Required for CCHS English II AP Seminar; this room covers the specified Young Readers Edition without reproducing it.",
  },
  {
    id: "intothewild", title: "Into the Wild", author: "Jon Krakauer", year: "1996",
    gradeBand: "9-12", grades: "11–12", themes: ["identity", "history"], rights: "copyrighted", status: "available", href: "intothewild/", accent: "#49643c",
    summary: "A nonlinear nonfiction investigation reconstructs Christopher McCandless’s travels and death through records, witnesses, geography, and contested interpretations.",
    why: "Required for CCHS English III AP / Dual Credit; teach source limits and uncertainty explicitly.",
  },
  {
    id: "survivorguilt", title: "The Moral Logic of Survivor Guilt", author: "Nancy Sherman", year: "2015",
    gradeBand: "9-12", grades: "10–12", themes: ["identity", "justice"], rights: "copyrighted", status: "available", href: "survivorguilt/", accent: "#63567a",
    summary: "A moral-psychology argument distinguishes causal blame from the guilt, loyalty, luck, and solidarity survivors may experience.",
    why: "A CCHS English II lens option; this trauma-aware companion reproduces no portion of the assigned excerpt.",
  },
  {
    id: "journeyintoself", title: "The Journey into the Self", author: "Joseph Campbell", year: "1949",
    gradeBand: "9-12", grades: "9–12", themes: ["identity"], rights: "copyrighted", status: "available", href: "journeyintoself/", accent: "#6b4f7d",
    summary: "A myth-criticism lens treats outward adventure as an inward transformation through thresholds, trials, encounters, and return.",
    why: "A CCHS English II Honors lens excerpt; use the pattern as a question, not a universal law.",
  },
  {
    id: "whywetellstories", title: "Why We Tell Stories", author: "Lisel Mueller", year: "1996",
    gradeBand: "9-12", grades: "9–12", themes: ["identity"], rights: "copyrighted", status: "available", href: "whywetellstories/", accent: "#79566d",
    summary: "A poem uses accumulation and recurring structure to consider storytelling as a response to uncertainty, memory, danger, desire, and community.",
    why: "A CCHS English II Honors lens option; students need the school-provided copyrighted poem.",
  },
  {
    id: "herosjourney", title: "The Hero’s Journey", author: "Joseph Campbell", year: "1949",
    gradeBand: "9-12", grades: "9–12", themes: ["identity", "power"], rights: "copyrighted", status: "available", href: "herosjourney/", accent: "#7a5a38",
    summary: "A critical-lens room tests the departure–initiation–return cycle against evidence while foregrounding the framework’s cultural limits.",
    why: "A CCHS English II AP Seminar lens excerpt; the companion emphasizes responsible, non-reductive use.",
  },
  {
    id: "dangersinglestory", title: "The Danger of a Single Story", author: "Chimamanda Ngozi Adichie", year: "2009",
    gradeBand: "9-12", grades: "9–12", themes: ["justice", "power"], rights: "copyrighted", status: "available", href: "dangersinglestory/", accent: "#8a4e3d",
    summary: "A personal argument shows how repeated partial narratives become stereotypes and how narrative power shapes cultural visibility.",
    why: "A CCHS English II AP Seminar lens transcript; the room links representation, evidence, and power.",
  },
  {
    id: "howtomarkabook", title: "How to Mark a Book", author: "Mortimer J. Adler", year: "1941",
    gradeBand: "9-12", grades: "11–12", themes: ["identity"], rights: "copyrighted", status: "available", href: "howtomarkabook/", accent: "#5d6640",
    summary: "An argument for active reading distinguishes physical possession from intellectual engagement through questions, connections, summaries, and marginal notes.",
    why: "Required for CCHS English III AP / Dual Credit; this room adds ethical alternatives for borrowed and digital texts.",
  },
];
