(function(){
'use strict';
const days=window.CONTRABAND_DAILY_OPENERS||[];const $=s=>document.querySelector(s);const page=$('#page'),live=$('#live');let index=0,gradeView='both',notesVisible=false;
const themeNames={justice:'Social Justice',history:'History and Memory',identity:'Identity and Belonging',power:'Censorship and Power'};
const themeLens={justice:{mid:'fairness, rights, and who gets treated differently',high:'justice, institutions, and unequal consequences'},history:{mid:'memory, evidence, and what people choose to remember',high:'historical memory, evidence, and whose account becomes official'},identity:{mid:'belonging, self-definition, and pressure to fit in',high:'identity, belonging, and the forces that shape self-definition'},power:{mid:'rules, control, voice, and who gets to decide',high:'authority, control, dissent, and who gets to define acceptable ideas'}};
const midPatterns=[
[['Notice',b=>`Study the image and title. What detail makes you curious about ${b.title}?`],['Think',(b,f)=>`The setup raises questions about ${themeLens[f].mid}. Which question feels most important?`],['Talk',b=>`What choice or conflict do you predict will matter most? Explain.`],['Write',b=>`Write one claim about what this book might ask readers to understand. Start with “This story may show that…”`]],
[['Predict',b=>`Based on the setup, what do you think someone in this story will want most?`],['Connect',(b,f)=>`Where have you seen a similar issue involving ${themeLens[f].mid} in history, another text, or real life?`],['Question',b=>`What would you ask one person in this situation before reading the book?`],['Write',b=>`Complete: “I would keep reading because I want to know whether…”`]],
[['Choose',b=>`Pick one word for the central conflict: courage, belonging, fairness, freedom, memory, or power. Defend your choice.`],['Evidence',b=>`Which detail in the setup best supports your choice?`],['Discuss',b=>`What might two reasonable readers disagree about before they even open this book?`],['Write',b=>`Write a two-sentence prediction: a claim, then your reason.`]],
[['Character',b=>`What pressure seems to be acting on the person or people in this setup?`],['Decision',b=>`What would be the hardest decision to make in this situation?`],['Connect',(b,f)=>`How can ${themeLens[f].mid} change what choices feel possible?`],['Write',b=>`Give advice to someone in the setup in 20 words or fewer.`]],
[['Title',b=>`What does the title ${b.title} make you expect before you know the plot?`],['Revise',b=>`Now read the setup. How did your first expectation change?`],['Talk',b=>`What is one topic a class could discuss using this book without needing to agree?`],['Write',b=>`Write a discussion question that cannot be answered with yes or no.`]],
[['Perspective',b=>`Whose point of view seems most important in this setup?`],['Missing voice',b=>`Whose perspective might be missing or less visible?`],['Connect',(b,f)=>`Why does perspective matter when people talk about ${themeLens[f].mid}?`],['Write',b=>`Write one sentence beginning, “The story might look different if…”`]],
[['Challenge',b=>`What makes this setup difficult, uncomfortable, or complicated?`],['Value',b=>`Why might readers still choose to examine a difficult story?`],['Talk',b=>`What classroom rule would help people discuss this topic respectfully?`],['Write',b=>`Finish: “A difficult book can be useful when…”`]]];
const highPatterns=[
[['Analyze',b=>`What system, belief, or power structure appears to drive the conflict in ${b.title}?`],['Interrogate',(b,f)=>`What assumption about ${themeLens[f].high} does this setup invite readers to question?`],['Discuss',b=>`Which tension looks most difficult to resolve, and why might reasonable people see it differently?`],['Write',b=>`Draft a two-sentence thesis: make a claim about the conflict, then name the tension that complicates it.`]],
[['Frame',b=>`Turn the setup into one debatable question worth a class discussion.`],['Context',(b,f)=>`What historical or social context would you need before making a strong judgment about ${themeLens[f].high}?`],['Counterpoint',b=>`What is one plausible position that could challenge your first reaction?`],['Write',b=>`Write a claim and one counterclaim. Keep both fair enough that someone could defend them.`]],
[['Power',b=>`Who has the most power in this setup, and what gives them that power?`],['Cost',b=>`Who pays the highest cost for the choices being made?`],['Connect',(b,f)=>`Name a current or historical situation that could illuminate ${themeLens[f].high}. Where does the comparison break down?`],['Write',b=>`Complete: “The central problem is not only ___; it is also ___ because…”`]],
[['Evidence',b=>`What fact would you most want to verify before discussing the issue raised by this setup?`],['Source',b=>`Whose testimony or evidence would be essential, and why?`],['Discuss',b=>`How could two people use the same facts and still reach different conclusions?`],['Write',b=>`Draft one evidence-seeking question that would make a discussion stronger.`]],
[['Voice',b=>`What voice or experience does this book place near the center of the conversation?`],['Silence',b=>`What becomes harder to understand if that perspective disappears from the record?`],['Challenge',b=>`What part of the subject is most likely to make a community disagree about classroom use?`],['Write',b=>`Write a two-sentence rationale for discussing a contested text without assuming everyone will agree about it.`]],
[['Interpret',b=>`What theme do you expect to matter most based on the setup? State it as a full idea, not one word.`],['Complicate',b=>`What detail prevents a simple good-versus-bad reading of the conflict?`],['Connect',(b,f)=>`How does the setup complicate a common belief about ${themeLens[f].high}?`],['Write',b=>`Draft an opening sentence for an analytical paragraph that begins with tension rather than summary.`]],
[['Decision',b=>`Identify the hardest decision implied by the setup. What values are in conflict?`],['Consequence',b=>`Which consequence should carry the most weight when evaluating that decision?`],['Discuss',b=>`What would count as a responsible disagreement about this choice?`],['Write',b=>`State your provisional position, then add one condition that could make you change it.`]]];
function assetBase(){return location.protocol==='file:'?'https://mguhlin.github.io/contraband/':'../'}function dayDate(n){return new Date(Date.UTC(2026,9,n))}function dateLabel(n){return new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}).format(dayDate(n))}function weekday(n){return new Intl.DateTimeFormat('en-US',{weekday:'long',timeZone:'UTC'}).format(dayDate(n))}function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function prompts(book,day,band,focus){const pat=(band==='g68'?midPatterns:highPatterns)[(day-1)%7];const lens=band==='g68'?'mid':'high';return pat.map(([label,fn])=>`<li class="prompt"><span class="prompt-label">${esc(label)}:</span><span>${esc(fn(book,focus,lens))}</span></li>`).join('')}
function setGradeView(view){gradeView=view;document.querySelectorAll('.grade-chip').forEach(b=>{const a=b.dataset.view===view;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))});const a=$('#g68Card'),b=$('#g912Card'),wrap=$('#openers');a.classList.toggle('hidden',view==='g912');b.classList.toggle('hidden',view==='g68');wrap.classList.toggle('single',view!=='both')}
function render(animate){const item=days[index];if(!item)return;const b=item.book,f=item.focus;if(animate){page.classList.remove('turn-next','turn-prev');void page.offsetWidth;page.classList.add(animate);setTimeout(()=>page.classList.remove(animate),360)}$('#weekdayLabel').textContent=weekday(item.day);$('#dayHeading').textContent=dateLabel(item.day);$('#dayNumber').textContent=String(item.day).padStart(2,'0');$('#focusLabel').textContent=themeNames[f]||f;$('#themeRibbon').textContent=themeNames[f]||f;$('#bookTitle').textContent=b.title;$('#bookByline').textContent=`${b.author} · ${b.year}`;$('#bookSetup').textContent=b.summary;$('#bookSetup').style.setProperty('--accent',b.accent);$('#bookImage').onerror=function(){this.onerror=null;this.src=assetBase()+'images/'+b.id+'/card.webp'};$('#bookImage').src=assetBase()+'images/'+b.id+'/hero.webp';$('#bookImage').alt='';$('#g68Prompts').innerHTML=prompts(b,item.day,'g68',f);$('#g912Prompts').innerHTML=prompts(b,item.day,'g912',f);$('#roomLink').href=assetBase()+b.id+'/';$('#counter').textContent=`Day ${item.day} of 31`;$('#prevBtn').disabled=index===0;$('#nextBtn').disabled=index===days.length-1;setGradeView(gradeView);document.querySelectorAll('.month-day').forEach(x=>x.classList.toggle('current',Number(x.dataset.day)===item.day));history.replaceState(null,'','#'+item.day);live.textContent=`October ${item.day}: ${b.title}. Grades 6 through 8 and grades 9 through 12 opener versions.`}
function go(n,dir){const next=Math.max(0,Math.min(days.length-1,n));if(next===index)return;index=next;render(dir==='prev'?'turn-prev':'turn-next');window.scrollTo({top:0,behavior:'smooth'})}
function buildMonth(){const grid=$('#monthGrid');grid.innerHTML='';const first=dayDate(1).getUTCDay();for(let i=0;i<first;i++){const blank=document.createElement('div');blank.className='month-blank';grid.appendChild(blank)}days.forEach(item=>{const b=document.createElement('button');b.type='button';b.className='month-day';b.dataset.day=item.day;b.innerHTML=`<span class="n">${item.day}</span><span class="tiny">${esc(item.book.title)}</span>`;b.addEventListener('click',()=>{index=item.day-1;closeMonth();render('turn-next');window.scrollTo({top:0,behavior:'smooth'})});grid.appendChild(b)})}
function openMonth(){$('#monthPanel').hidden=false;$('#monthBtn').setAttribute('aria-expanded','true');document.body.style.overflow='hidden';setTimeout(()=>$('#closeMonth').focus(),0)}function closeMonth(){$('#monthPanel').hidden=true;$('#monthBtn').setAttribute('aria-expanded','false');document.body.style.overflow='';$('#monthBtn').focus()}
function init(){if(!days.length){page.innerHTML='<p>Daily opener data could not be loaded.</p>';return}buildMonth();const hash=Number((location.hash||'').replace('#',''));index=hash>=1&&hash<=31?hash-1:0;$('#prevBtn').addEventListener('click',()=>go(index-1,'prev'));$('#nextBtn').addEventListener('click',()=>go(index+1,'next'));document.querySelectorAll('.grade-chip').forEach(b=>b.addEventListener('click',()=>setGradeView(b.dataset.view)));$('#monthBtn').addEventListener('click',openMonth);$('#closeMonth').addEventListener('click',closeMonth);$('#monthPanel').addEventListener('click',e=>{if(e.target.id==='monthPanel')closeMonth()});$('#notesBtn').addEventListener('click',()=>{notesVisible=!notesVisible;$('#teacherNote').hidden=!notesVisible;$('#notesBtn').setAttribute('aria-pressed',String(notesVisible))});$('#printBtn').addEventListener('click',()=>window.print());$('#fullBtn').addEventListener('click',()=>{if(!document.fullscreenElement){document.documentElement.requestFullscreen?.()}else{document.exitFullscreen?.()}});document.addEventListener('keydown',e=>{if(!$('#monthPanel').hidden&&e.key==='Escape'){closeMonth();return}if(e.target.closest('button,a,input,textarea,select'))return;if(e.key==='ArrowRight'||e.key==='PageDown'){go(index+1,'next');e.preventDefault()}if(e.key==='ArrowLeft'||e.key==='PageUp'){go(index-1,'prev');e.preventDefault()}if(e.key==='Home'){index=0;render('turn-prev')}if(e.key==='End'){index=30;render('turn-next')}});render()}
init();
})();
