/* Contraband — The Moral Logic of Survivor Guilt. Generated by _build_cchs_summer.js. */
window.__ROOM__ = {
  "id": "survivorguilt",
  "storageKey": "contraband.survivorguilt.v1",
  "ui": {
    "skip": "Skip to the activity",
    "brand.tag": "Read · Reason · Play",
    "reset": "Reset",
    "reset.confirm": "Reset this room and clear saved progress on this device?",
    "footer.tagline": "No logins · no accounts · no data collected · runs entirely in your browser.",
    "footer.privacy": "Privacy & compliance",
    "footer.back": "All Contraband rooms",
    "review.flag": "Needs review",
    "progress.chip": "{n}/{total} activities done",
    "nav.enter": "Enter the Story",
    "nav.vocab": "Vocabulary",
    "nav.relic": "Relic Room",
    "nav.ctob": "Crack the Case",
    "nav.arcade": "Arcade Game",
    "nav.analysis": "Analyze the Text",
    "nav.extend": "Extend the Idea",
    "nav.genai": "Gen AI Partner",
    "nav.print": "Print Materials",
    "nav.teacher": "Teacher Guide",
    "nav.done": "completed",
    "enter.eyebrow": "Enter the Story",
    "enter.by": "by {a}",
    "enter.spoiler": "Spoiler level",
    "enter.access": "Text access",
    "enter.copyright": "Copyright",
    "enter.contentReview": "Content-review note",
    "enter.contentDefault": "Districts should review edition, maturity level, local policy, instructional purpose, student needs, and community expectations.",
    "enter.goals": "Learning goals",
    "enter.stages": "When to use this room",
    "enter.stage.before": "Before reading",
    "enter.stage.during": "During reading",
    "enter.stage.after": "After reading",
    "enter.aceEyebrow": "Thinking routine",
    "enter.ace": "The ACE Framework",
    "enter.aceIntro": "Every task in this room asks you to Articulate, Connect, and Extend your thinking.",
    "enter.readListen": "Read & Listen",
    "enter.readListenTitle": "Get the text",
    "enter.readListenNote": "This is a copyrighted novel; students need lawful access to their own copy. This activity does not link to or reproduce the text.",
    "enter.read": "Find the book",
    "enter.listen": "Audiobook",
    "enter.readAloud": "Use your class's licensed copy or audiobook.",
    "ace.articulate": "A · Articulate",
    "ace.connect": "C · Connect",
    "ace.extend": "E · Extend",
    "vocab.eyebrow": "Build Your Vocabulary",
    "vocab.title": "Words for The Moral Logic of Survivor Guilt",
    "vocab.intro": "{n} terms that support close reading of the assigned work. Study them, match them, then test them in context.",
    "vocab.mode.study": "Study cards",
    "vocab.mode.match": "Matching",
    "vocab.mode.context": "Context clues",
    "vocab.example": "Example",
    "vocab.nonexample": "Nonexample",
    "vocab.matchHint": "Select a term, then select its meaning. Correct pairs lock in.",
    "vocab.terms": "Terms",
    "vocab.defs": "Meanings",
    "vocab.matchDone": "All terms matched. Nicely reasoned.",
    "vocab.contextLabel": "Choose the word that fits",
    "vocab.noContext": "Context sentences are coming soon for this room.",
    "relic.eyebrow": "Explore the Relic Room",
    "relic.title": "The Moral Logic of Survivor Guilt: Evidence Lab",
    "relic.reviewed": "Reviewed",
    "relic.investigate": "Investigate",
    "relic.placeholder": "Image placeholder",
    "relic.artifact": "Artifact {n}",
    "relic.q.identify": "Identify it — what is this?",
    "relic.q.purpose": "Explain its role in the novel",
    "relic.q.significance": "What it reveals about the story's meaning",
    "relic.check": "Check my investigation",
    "relic.answerAll": "Answer all three questions before checking.",
    "relic.scored": "You reasoned {c} of {m} correct. Read the reveal, then respond.",
    "relic.reveals": "What it reveals",
    "relic.conceals": "What it may conceal",
    "relic.aceLabel": "ACE response",
    "relic.aceDefault": "Articulate what this artifact shows, connect it to a theme, and extend it to a question it raises.",
    "relic.acePlaceholder": "Write your ACE response (stays on this device)…",
    "ctob.eyebrow": "Crack the Case",
    "ctob.title": "The Evidence Chain",
    "ctob.progress": "{n} of {total} locks opened",
    "ctob.done": "Every lock is open. The case is solved — with evidence.",
    "ctob.lock": "Lock {n}",
    "lock.digit": "Number lock",
    "lock.word": "Word lock",
    "lock.mc": "Choice lock",
    "lock.sequence": "Sequence lock",
    "ctob.correct": "Open — the evidence supports it.",
    "ctob.enter": "Enter your answer",
    "ctob.check": "Check",
    "ctob.wrong": "Not yet — re-read the evidence and try again.",
    "ctob.hint": "Show a hint",
    "seq.up": "Move up",
    "seq.down": "Move down",
    "arcade.eyebrow": "Play the Arcade Game",
    "arcade.title": "Claim or Evidence?",
    "arcade.default": "Sort each statement by whether it is a real idea the fable teaches or part of Santiago's invented plot.",
    "arcade.drophere": "Drop cards here — or use the buttons on each card.",
    "arcade.moveto": "Move to {b}",
    "arcade.placedn": "{n} of {total} cards sorted",
    "arcade.check": "Check my reasoning",
    "arcade.replay": "Play again",
    "arcade.placeAll": "Sort every card before checking.",
    "arcade.result": "{c} of {total} sorted with sound reasoning.",
    "arcade.cards": "Statements to sort",
    "arcade.followup": "Discuss / write",
    "analysis.eyebrow": "Analyze the Text",
    "analysis.title": "Literary Analysis",
    "analysis.intro": "Five evidence questions, then written responses. Every question rewards the best-supported reading.",
    "analysis.mc": "Question {n}",
    "analysis.check": "Check my answers",
    "analysis.answerAll": "Answer all five questions first.",
    "analysis.score": "{c} of {total} best-supported answers.",
    "analysis.written": "Written responses",
    "analysis.writtenIntro": "These stay on your device. Print them from the Print Materials tab.",
    "analysis.short": "Short response {n}",
    "analysis.paragraph": "Evidence paragraph",
    "analysis.aceReflection": "ACE reflection",
    "analysis.localNote": "Your writing is never sent anywhere — it stays in this browser.",
    "extend.eyebrow": "Extend the Idea",
    "extend.title": "Then into Now",
    "extend.format": "Format",
    "extend.evidence": "The idea from the assigned source I am building on",
    "extend.transfers": "What transfers to the present",
    "extend.changes": "What changes in a modern setting",
    "extend.breaks": "Where the comparison stops working",
    "extend.response": "My evidence-based comparison",
    "extend.localNote": "Your response stays on this device. You own it.",
    "genai.eyebrow": "Gen AI Thinking Partner",
    "genai.title": "Optional Gen AI Support",
    "genai.rule": "Think first. Use Gen AI after effort, not before it. Never let Gen AI replace your reasoning.",
    "genai.enable": "Teacher: enable Gen AI supports on this device",
    "genai.enableNote": "Off by default. This setting is stored only in this browser and is never transmitted.",
    "genai.warning": "Never paste names, private information, or another person's writing. Use only district-approved tools.",
    "genai.prompts": "Copyable prompts",
    "genai.copy": "Copy",
    "genai.copied": "Copied ✓",
    "genai.receipt": "Gen AI Thinking Receipt",
    "genai.receiptIntro": "If you use Gen AI, complete this receipt so your reasoning stays yours. It stays on this device.",
    "genai.before": "Before Gen AI",
    "genai.during": "Gen AI interaction",
    "genai.after": "After Gen AI",
    "r.first": "1. My first explanation",
    "r.evidence": "2. My initial evidence",
    "r.question": "3. My unanswered question",
    "r.asked": "4. What I asked",
    "r.suggested": "5. What the tool suggested",
    "r.accepted": "6. What I accepted",
    "r.changed": "7. What I changed",
    "r.rejected": "8. What I rejected",
    "r.why": "9. Why I made those choices",
    "r.textEvidence": "10. My evidence from the text",
    "r.final": "11. My final ACE response",
    "genai.altTitle": "Non-AI alternative",
    "genai.alt": "Prefer no AI? Trade receipts with a partner and interview each other with the same questions, or use the printed thinking sheet.",
    "print.eyebrow": "Print Student Materials",
    "print.title": "Printable Packet",
    "print.intro": "Print a no-login paper packet for this room. Use your browser's print dialog to save as PDF.",
    "print.item.vocab": "Vocabulary reference",
    "print.item.relic": "Keepsakes evidence sheet",
    "print.item.ctob": "Breakout evidence sheet",
    "print.item.analysis": "Analysis questions",
    "print.item.extend": "Then-into-now organizer",
    "print.item.ace": "ACE organizer",
    "print.item.receipt": "Gen AI thinking receipt",
    "print.button": "Print / Save as PDF",
    "print.answer": "Answer:",
    "teacher.eyebrow": "Teacher Guide",
    "teacher.title": "For the Educator",
    "teacher.pathways": "Assignment pathways",
    "teacher.standards": "Standards & supports",
    "teacher.standardsNote": "This room is aligned to — not reproduced from — the standards below. Confirm codes against your current adoption.",
    "teacher.framework": "Framework",
    "teacher.codes": "Alignment",
    "teacher.answerKeys": "Answer keys (educator reference)",
    "teacher.answerNote": "These are provided for teachers. Assign the student tabs before revealing keys.",
    "teacher.reviewItems": "Items to verify before teaching",
    "path.quick": "Quick Play",
    "path.quick.time": "15–25 minutes",
    "path.quick.body": "Vocabulary preview, arcade game, five-question check, one Articulate response.",
    "path.invest": "Investigation",
    "path.invest.time": "30–45 minutes",
    "path.invest.body": "Relic Room, evidence organizer, one Connect response, optional discussion.",
    "path.complete": "Complete Case",
    "path.complete.time": "60–90 minutes / multiple periods",
    "path.complete.body": "Vocabulary, Relic Room, breakout, arcade, analysis, extend task, ACE reflection."
  },
  "content": {
    "meta": {
      "title": "The Moral Logic of Survivor Guilt",
      "author": "Nancy Sherman",
      "grades": "Grades 10–12",
      "genre": "Argument / moral psychology",
      "time": "45–75 minutes",
      "spoiler": "Assignment-aligned",
      "rights": "Copyrighted",
      "hero": "images/hero.webp",
      "heroAlt": "Original thematic illustration for The Moral Logic of Survivor Guilt",
      "compactNotices": true,
      "noticeLabel": "Access, copyright & content notes",
      "textAccess": "Students need lawful access to the school-assigned source. This room does not reproduce, quote, or link to it.",
      "copyright": "The Moral Logic of Survivor Guilt is treated as copyrighted. This independent companion is paraphrase-only and quotation-free.",
      "contentNote": "The assigned excerpt concerns trauma, death, war, disaster, guilt, responsibility, and survival. Provide opt-out pathways and trauma-aware discussion norms.",
      "disclaimer": "This activity is an independent educational companion to The Moral Logic of Survivor Guilt by Nancy Sherman. Students need lawful access to the assigned source. It does not reproduce or replace the source, quotes no passages, and links to no unauthorized copy. It is not affiliated with or endorsed by the author or publisher. Original activity content is CC BY-NC 4.0; the source remains the property of its copyright owner and is excluded from that license."
    },
    "hook": "Nancy Sherman examines survivor guilt as a moral emotion: people may feel implicated in another person’s suffering even when they did not cause it or could not have prevented it. The argument asks readers to distinguish causal blame from loyalty, luck, solidarity, and the wish to have done more.",
    "goals": [
      "Distinguish guilt feelings from legal or causal culpability.",
      "Trace the moral reasoning that can make survivor guilt intelligible.",
      "Evaluate when guilt honors relationship and when it distorts responsibility.",
      "Apply the framework carefully without diagnosing real people."
    ],
    "stages": {
      "before": [
        "Preview the vocabulary and content-review note.",
        "Record an initial question the title or assignment raises."
      ],
      "during": [
        "Use the evidence lab to track details in the lawful assigned copy.",
        "Separate observation, inference, and evaluation in notes."
      ],
      "after": [
        "Run the evidence chain and analysis.",
        "Complete an ACE transfer without replacing source evidence with summary."
      ]
    },
    "ace": {
      "articulate": {
        "goal": "Explain one idea.",
        "prompt": "Explain one central idea in The Moral Logic of Survivor Guilt in your own words."
      },
      "connect": {
        "goal": "Connect evidence.",
        "prompt": "Connect two source details and explain why their relationship matters."
      },
      "extend": {
        "goal": "Test transfer.",
        "prompt": "Apply one idea to a new context and identify where the comparison breaks."
      }
    },
    "vocab": [
      {
        "term": "survivor guilt",
        "def": "distress about living or remaining unharmed when others did not",
        "example": "A reader could use survivor guilt to analyze a specific choice, pattern, or claim in The Moral Logic of Survivor Guilt.",
        "nonexample": "Naming survivor guilt without explaining evidence or effect.",
        "context": "Use survivor guilt precisely when discussing the assigned source."
      },
      {
        "term": "culpability",
        "def": "deserving blame for wrongdoing",
        "example": "A reader could use culpability to analyze a specific choice, pattern, or claim in The Moral Logic of Survivor Guilt.",
        "nonexample": "Naming culpability without explaining evidence or effect.",
        "context": "Use culpability precisely when discussing the assigned source."
      },
      {
        "term": "moral luck",
        "def": "the role chance plays in outcomes that affect moral judgment",
        "example": "A reader could use moral luck to analyze a specific choice, pattern, or claim in The Moral Logic of Survivor Guilt.",
        "nonexample": "Naming moral luck without explaining evidence or effect.",
        "context": "Use moral luck precisely when discussing the assigned source."
      },
      {
        "term": "solidarity",
        "def": "identification and mutual responsibility within a group",
        "example": "A reader could use solidarity to analyze a specific choice, pattern, or claim in The Moral Logic of Survivor Guilt.",
        "nonexample": "Naming solidarity without explaining evidence or effect.",
        "context": "Use solidarity precisely when discussing the assigned source."
      },
      {
        "term": "counterfactual",
        "def": "an imagined alternative to what actually happened",
        "example": "A reader could use counterfactual to analyze a specific choice, pattern, or claim in The Moral Logic of Survivor Guilt.",
        "nonexample": "Naming counterfactual without explaining evidence or effect.",
        "context": "Use counterfactual precisely when discussing the assigned source."
      },
      {
        "term": "agency",
        "def": "the capacity to choose and act",
        "example": "A reader could use agency to analyze a specific choice, pattern, or claim in The Moral Logic of Survivor Guilt.",
        "nonexample": "Naming agency without explaining evidence or effect.",
        "context": "Use agency precisely when discussing the assigned source."
      },
      {
        "term": "complicity",
        "def": "involvement in wrongdoing",
        "example": "A reader could use complicity to analyze a specific choice, pattern, or claim in The Moral Logic of Survivor Guilt.",
        "nonexample": "Naming complicity without explaining evidence or effect.",
        "context": "Use complicity precisely when discussing the assigned source."
      },
      {
        "term": "moral emotion",
        "def": "a feeling tied to judgments about responsibility or value",
        "example": "A reader could use moral emotion to analyze a specific choice, pattern, or claim in The Moral Logic of Survivor Guilt.",
        "nonexample": "Naming moral emotion without explaining evidence or effect.",
        "context": "Use moral emotion precisely when discussing the assigned source."
      }
    ],
    "relic": {
      "name": "The Moral Logic of Survivor Guilt: Evidence Lab",
      "intro": "Five original instructional reconstructions. They are prompts for investigation, not source text or publisher artwork.",
      "artifacts": [
        {
          "id": "artifact-1",
          "name": "unequal outcomes",
          "image": "images/artifact-1.webp",
          "clues": [
            "This instructional reconstruction represents unequal outcomes.",
            "Different outcomes can produce guilt even without different intentions.",
            "Use the assigned source to verify how unequal outcomes contributes to the work."
          ],
          "identify": {
            "q": "What does this reconstruction represent?",
            "choices": [
              "unequal outcomes",
              "An unrelated object",
              "A quotation from the source",
              "A publisher’s illustration"
            ]
          },
          "purpose": {
            "q": "Why is it included?",
            "choices": [
              "Different outcomes can produce guilt even without different intentions.",
              "It replaces reading the assigned source",
              "It proves every interpretation",
              "It supplies an exact quotation"
            ]
          },
          "significance": {
            "q": "What should a reader do next?",
            "choices": [
              "Connect unequal outcomes to a specific detail in the assigned source.",
              "Treat the reconstruction as the original text.",
              "Ignore context and edition.",
              "Assume one symbol settles the work."
            ]
          },
          "reveals": "Different outcomes can produce guilt even without different intentions.",
          "conceals": "The exact language, context, and complexity that must be checked in the assigned source.",
          "ace": "Articulate what unequal outcomes shows, connect it to a larger idea, and test the connection against the source."
        },
        {
          "id": "artifact-2",
          "name": "counterfactual question",
          "image": "images/artifact-2.webp",
          "clues": [
            "This instructional reconstruction represents counterfactual question.",
            "Imagined alternatives keep asking what a survivor might have done.",
            "Use the assigned source to verify how counterfactual question contributes to the work."
          ],
          "identify": {
            "q": "What does this reconstruction represent?",
            "choices": [
              "counterfactual question",
              "An unrelated object",
              "A quotation from the source",
              "A publisher’s illustration"
            ]
          },
          "purpose": {
            "q": "Why is it included?",
            "choices": [
              "Imagined alternatives keep asking what a survivor might have done.",
              "It replaces reading the assigned source",
              "It proves every interpretation",
              "It supplies an exact quotation"
            ]
          },
          "significance": {
            "q": "What should a reader do next?",
            "choices": [
              "Connect counterfactual question to a specific detail in the assigned source.",
              "Treat the reconstruction as the original text.",
              "Ignore context and edition.",
              "Assume one symbol settles the work."
            ]
          },
          "reveals": "Imagined alternatives keep asking what a survivor might have done.",
          "conceals": "The exact language, context, and complexity that must be checked in the assigned source.",
          "ace": "Articulate what counterfactual question shows, connect it to a larger idea, and test the connection against the source."
        },
        {
          "id": "artifact-3",
          "name": "unit bond",
          "image": "images/artifact-3.webp",
          "clues": [
            "This instructional reconstruction represents unit bond.",
            "Loyalty can make another person’s loss feel personally implicating.",
            "Use the assigned source to verify how unit bond contributes to the work."
          ],
          "identify": {
            "q": "What does this reconstruction represent?",
            "choices": [
              "unit bond",
              "An unrelated object",
              "A quotation from the source",
              "A publisher’s illustration"
            ]
          },
          "purpose": {
            "q": "Why is it included?",
            "choices": [
              "Loyalty can make another person’s loss feel personally implicating.",
              "It replaces reading the assigned source",
              "It proves every interpretation",
              "It supplies an exact quotation"
            ]
          },
          "significance": {
            "q": "What should a reader do next?",
            "choices": [
              "Connect unit bond to a specific detail in the assigned source.",
              "Treat the reconstruction as the original text.",
              "Ignore context and edition.",
              "Assume one symbol settles the work."
            ]
          },
          "reveals": "Loyalty can make another person’s loss feel personally implicating.",
          "conceals": "The exact language, context, and complexity that must be checked in the assigned source.",
          "ace": "Articulate what unit bond shows, connect it to a larger idea, and test the connection against the source."
        },
        {
          "id": "artifact-4",
          "name": "responsibility scale",
          "image": "images/artifact-4.webp",
          "clues": [
            "This instructional reconstruction represents responsibility scale.",
            "Causal control and emotional burden do not always match.",
            "Use the assigned source to verify how responsibility scale contributes to the work."
          ],
          "identify": {
            "q": "What does this reconstruction represent?",
            "choices": [
              "responsibility scale",
              "An unrelated object",
              "A quotation from the source",
              "A publisher’s illustration"
            ]
          },
          "purpose": {
            "q": "Why is it included?",
            "choices": [
              "Causal control and emotional burden do not always match.",
              "It replaces reading the assigned source",
              "It proves every interpretation",
              "It supplies an exact quotation"
            ]
          },
          "significance": {
            "q": "What should a reader do next?",
            "choices": [
              "Connect responsibility scale to a specific detail in the assigned source.",
              "Treat the reconstruction as the original text.",
              "Ignore context and edition.",
              "Assume one symbol settles the work."
            ]
          },
          "reveals": "Causal control and emotional burden do not always match.",
          "conceals": "The exact language, context, and complexity that must be checked in the assigned source.",
          "ace": "Articulate what responsibility scale shows, connect it to a larger idea, and test the connection against the source."
        },
        {
          "id": "artifact-5",
          "name": "repair action",
          "image": "images/artifact-5.webp",
          "clues": [
            "This instructional reconstruction represents repair action.",
            "Service or testimony may express solidarity without falsely confessing blame.",
            "Use the assigned source to verify how repair action contributes to the work."
          ],
          "identify": {
            "q": "What does this reconstruction represent?",
            "choices": [
              "repair action",
              "An unrelated object",
              "A quotation from the source",
              "A publisher’s illustration"
            ]
          },
          "purpose": {
            "q": "Why is it included?",
            "choices": [
              "Service or testimony may express solidarity without falsely confessing blame.",
              "It replaces reading the assigned source",
              "It proves every interpretation",
              "It supplies an exact quotation"
            ]
          },
          "significance": {
            "q": "What should a reader do next?",
            "choices": [
              "Connect repair action to a specific detail in the assigned source.",
              "Treat the reconstruction as the original text.",
              "Ignore context and edition.",
              "Assume one symbol settles the work."
            ]
          },
          "reveals": "Service or testimony may express solidarity without falsely confessing blame.",
          "conceals": "The exact language, context, and complexity that must be checked in the assigned source.",
          "ace": "Articulate what repair action shows, connect it to a larger idea, and test the connection against the source."
        }
      ]
    },
    "ctob": {
      "name": "The Evidence Chain",
      "intro": "Open six locks using the assigned source and the paraphrased evidence provided here.",
      "locks": [
        {
          "type": "word",
          "prompt": "What is the first word in this room’s thinking routine: Articulate, Connect, Extend?",
          "evidence": [
            "It means explain clearly in your own words."
          ],
          "hints": [
            "It begins with A.",
            "It is Articulate."
          ],
          "answer": "articulate"
        },
        {
          "type": "sequence",
          "prompt": "Put the assigned work’s major movement in order.",
          "items": [
            "A survivor confronts an unequal outcome.",
            "Counterfactual thinking asks why one person lived or remained safe.",
            "Moral analysis separates causal blame from loyalty and luck.",
            "A constructive response seeks truthful responsibility and meaningful connection."
          ],
          "hints": [
            "Start with the earliest condition.",
            "Follow cause before consequence.",
            "Use the listed order after checking the source."
          ]
        },
        {
          "type": "mc",
          "prompt": "Sherman treats survivor guilt as morally intelligible because —",
          "options": [
            "relationships and solidarity can generate responsibility-like feelings beyond causal blame.",
            "A distractor unsupported by the source.",
            "A conclusion that reverses cause and effect.",
            "A claim that ignores context."
          ],
          "hints": [
            "Choose the answer best supported by the assigned source."
          ]
        },
        {
          "type": "mc",
          "prompt": "A counterfactual matters because —",
          "options": [
            "imagining a different action can intensify guilt even when the alternative was impossible.",
            "A distractor unsupported by the source.",
            "A conclusion that reverses cause and effect.",
            "A claim that ignores context."
          ],
          "hints": [
            "Choose the answer best supported by the assigned source."
          ]
        },
        {
          "type": "mc",
          "prompt": "The distinction between guilt and culpability —",
          "options": [
            "prevents strong feeling from automatically proving wrongdoing.",
            "A distractor unsupported by the source.",
            "A conclusion that reverses cause and effect.",
            "A claim that ignores context."
          ],
          "hints": [
            "Choose the answer best supported by the assigned source."
          ]
        },
        {
          "type": "mc",
          "prompt": "Calling the emotion irrational too quickly may —",
          "options": [
            "miss the loyalty and moral concern expressed by the feeling.",
            "A distractor unsupported by the source.",
            "A conclusion that reverses cause and effect.",
            "A claim that ignores context."
          ],
          "hints": [
            "Choose the answer best supported by the assigned source."
          ]
        }
      ]
    },
    "arcade": {
      "name": "Claim or Evidence?",
      "instruction": "Sort analytical concepts from concrete source details. A strong paragraph needs both.",
      "buckets": [
        {
          "id": "claim",
          "label": "Analytical claim",
          "short": "Claim"
        },
        {
          "id": "evidence",
          "label": "Source detail",
          "short": "Evidence"
        }
      ],
      "cards": [
        {
          "text": "survivor guilt: distress about living or remaining unharmed when others did not",
          "bucket": "claim",
          "why": "This is an analytical concept that can organize a claim."
        },
        {
          "text": "culpability: deserving blame for wrongdoing",
          "bucket": "claim",
          "why": "This is an analytical concept that can organize a claim."
        },
        {
          "text": "moral luck: the role chance plays in outcomes that affect moral judgment",
          "bucket": "claim",
          "why": "This is an analytical concept that can organize a claim."
        },
        {
          "text": "solidarity: identification and mutual responsibility within a group",
          "bucket": "claim",
          "why": "This is an analytical concept that can organize a claim."
        },
        {
          "text": "unequal outcomes — Different outcomes can produce guilt even without different intentions.",
          "bucket": "evidence",
          "why": "This identifies a source-grounded detail that must be explained."
        },
        {
          "text": "counterfactual question — Imagined alternatives keep asking what a survivor might have done.",
          "bucket": "evidence",
          "why": "This identifies a source-grounded detail that must be explained."
        },
        {
          "text": "unit bond — Loyalty can make another person’s loss feel personally implicating.",
          "bucket": "evidence",
          "why": "This identifies a source-grounded detail that must be explained."
        },
        {
          "text": "responsibility scale — Causal control and emotional burden do not always match.",
          "bucket": "evidence",
          "why": "This identifies a source-grounded detail that must be explained."
        }
      ],
      "followup": "Choose one claim and one evidence card. Explain the reasoning that connects them, then verify it in the assigned source."
    },
    "analysis": {
      "mcq": [
        {
          "q": "Sherman treats survivor guilt as morally intelligible because —",
          "options": [
            "relationships and solidarity can generate responsibility-like feelings beyond causal blame.",
            "a claim the source does not support.",
            "a detail that ignores the work’s structure.",
            "a conclusion based only on assumption."
          ],
          "why": "relationships and solidarity can generate responsibility-like feelings beyond causal blame."
        },
        {
          "q": "A counterfactual matters because —",
          "options": [
            "imagining a different action can intensify guilt even when the alternative was impossible.",
            "a claim the source does not support.",
            "a detail that ignores the work’s structure.",
            "a conclusion based only on assumption."
          ],
          "why": "imagining a different action can intensify guilt even when the alternative was impossible."
        },
        {
          "q": "The distinction between guilt and culpability —",
          "options": [
            "prevents strong feeling from automatically proving wrongdoing.",
            "a claim the source does not support.",
            "a detail that ignores the work’s structure.",
            "a conclusion based only on assumption."
          ],
          "why": "prevents strong feeling from automatically proving wrongdoing."
        },
        {
          "q": "Calling the emotion irrational too quickly may —",
          "options": [
            "miss the loyalty and moral concern expressed by the feeling.",
            "a claim the source does not support.",
            "a detail that ignores the work’s structure.",
            "a conclusion based only on assumption."
          ],
          "why": "miss the loyalty and moral concern expressed by the feeling."
        },
        {
          "q": "A constructive response should —",
          "options": [
            "honor connection while keeping claims about actual control accurate.",
            "a claim the source does not support.",
            "a detail that ignores the work’s structure.",
            "a conclusion based only on assumption."
          ],
          "why": "honor connection while keeping claims about actual control accurate."
        }
      ],
      "short": [
        "Choose one turning point or argumentative move and explain how it changes the work’s meaning.",
        "Identify one reasonable alternative interpretation and explain what evidence would test it."
      ],
      "paragraph": "Make a defensible claim about The Moral Logic of Survivor Guilt. Support it with precise evidence from the lawful assigned source and explain the reasoning between them.",
      "aceReflection": "What became clearer when you connected a concrete detail to a larger claim?"
    },
    "extend": {
      "name": "Then into Now",
      "prompt": "Transfer one idea from the assigned work to a present-day situation. State what transfers, what changes, and where the analogy stops working.",
      "format": "A short evidence-based comparison with an explicit limit."
    },
    "genaiPrompts": [
      {
        "title": "Articulate",
        "text": "Ask me one question at a time that helps me explain an idea from The Moral Logic of Survivor Guilt; do not write my answer."
      },
      {
        "title": "Evidence",
        "text": "Ask whether my selected evidence is relevant, sufficient, and accurately paraphrased."
      },
      {
        "title": "Connect",
        "text": "Challenge the reasoning connecting my evidence to my claim."
      },
      {
        "title": "Alternative",
        "text": "Offer one plausible counterreading as a question."
      },
      {
        "title": "Copyright-safe help",
        "text": "Discuss concepts without supplying or imitating copyrighted passages."
      },
      {
        "title": "Critique",
        "text": "Identify assumptions and missing evidence; respond with questions only."
      }
    ],
    "teacher": {
      "overview": "A quotation-free independent companion to The Moral Logic of Survivor Guilt, designed around vocabulary, evidence classification, causal sequence, literary or rhetorical analysis, and ACE transfer.",
      "reviewNotes": [
        "The assigned excerpt concerns trauma, death, war, disaster, guilt, responsibility, and survival. Provide opt-out pathways and trauma-aware discussion norms.",
        "Confirm the exact school-assigned edition or excerpt and course expectations.",
        "Translations and standards require local human review."
      ]
    },
    "standards": {
      "teks": "Aligned to secondary ELAR response, comprehension, author’s craft, composition, and inquiry strands. Confirm exact course expectations. (Needs review)",
      "elps": "Supports listening, speaking, reading, and writing through vocabulary, structured talk, visuals, and evidence frames. (Needs review)",
      "ccss": "CCSS secondary reading, writing, speaking/listening, and language strands appropriate to the assigned course. (Needs review)",
      "udl": "Multiple means of engagement, representation, and expression; keyboard/touch access; printable alternatives; no timer."
    }
  }
};
